### ISSUE TITLE
[question] primary keys as fully qualified names 

### ISSUE THREAD

**Issue by ferinoc** [redis/redis-om-spring#107]
In  this presentation was shown that keys/data are stored as keys as fully qualified names 
https://www.youtube.com/watch?v=ub-jDOb7jEM
What happens if we rename "dbo" classes or move to different package, please?

**Comment by bsbodden** [comment]
If you rename your classes or move them to a different package you have 2 options:

1. **Easy**: Use the `value` on the `@Document` annotation, that overrides the key prefix for the collection:

```
@Document("myKeyPrefix")
public class Permit {
  @Id
  private String id;
//...
```

2. **Not so easy**: Rename the keys to the new fully qualified package using the RENAME command https://redis.io/commands/rename/
