### ISSUE TITLE
[question] Is possible search via Java predicate?

### ISSUE THREAD

**Issue by ferinoc** [redis/redis-om-spring#108]
Is possible search via Java predicate or only via SearchFieldPredicate ?
![image](https://user-images.githubusercontent.com/1408155/191067887-5e2d2cfd-b698-4e1b-a703-4ea31dd25200.png)

Thank you again.
Frantisek

**Comment by bsbodden** [comment]
Not currently, Java lambdas and not like .Net lambdas, they're not easily parseable and it slightly changes from JVM to JVM (a lot of byte-level changes). So until the Java language provides a clean way to parse Lambdas into an AST we're out of luck. I haven't check the Java 17-18-19 specs for this but up to 11-15 we still a no-go in that respect.
