### ISSUE TITLE
Return specific key/values from a document using EntityStream

### ISSUE THREAD

**Issue by Nikhilkdm3** [redis/redis-om-spring#110]
Hello,

I'm attempting to extract specific key/value pairs from a document using EntityStream. I used .map, but it returns a Pair/Triple response based on the number of fields specified.

I have included some sample code below for better understanding.

**With all fields:**

`return entityStream .of(Company.class) .limit(2).collect(Collectors.toList()); // this will return to the controller and it produces json.`

An example response in the browser/postman:

```
[{
"name": "xyz-company1",
"year_founded": 2019,
"description": "example description"
"owner": "nikhil"
},
{
"name": "xyz-company2",
"year_founded": 2020,
"description": "example description2"
"owner": "brian"
}]
```
**Limit number of fields:**

`return entityStream .of(Company.class).sorted(Company$.NAME, SortOrder.DESC).map(Fields.of(Company$.NAME, Company$.YEAR_FOUNDED)).limit(1).collect(Collectors.toList()); // this will return to the controller and it produces json.`

console log:
`[PairImpl {xyz-company, 2019}]`

An example response in the browser/postman:

```
[{
"first": "xyz-company1",
"second": "2019"
}]
```

You can see the differences between their responses. The first example returns key-value pairs, but the second does not.

The expected response to the second scenario is,

```
[{
"name": "xyz-company1",
"year_founded": 2019
}]
```

**Comment by bsbodden** [comment]
FYI https://github.com/redis/redis-om-spring/pull/115

**Comment by bsbodden** [comment]
@Nikhilkdm3 This is implemented in https://central.sonatype.dev/artifact/com.redis.om/redis-om-spring/0.6.1
