### ISSUE TITLE
Adding Redis om spring dependency in spring cloud stream project gives startup error

### ISSUE THREAD

**Issue by praks84** [redis/redis-om-spring#111]
Hello,

I have a spring cloud stream project with kafka streams binder dependency - no issues at startup.
Next I add redis om spring dependency 0.6.0, add a model object annotate it with @Document and annotate main class with @EnableRedisDocumentRepositories. Now I get below error at startup

Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
at com.redis.om.spring.RedisModulesConfiguration.getBeanDefinitionsFor(RedisModulesConfiguration.java:392)

Apologies for any mistake in posting this issue with details - new to this, so please guide me.

**Comment by roux-jerome** [comment]
same issue

**Comment by roux-jerome** [comment]
```java
Map<String, Object> annotatedBeans = ac.getBeansWithAnnotation(SpringBootApplication.class); // return an empty LinkedHashMap
Class<?> app = annotatedBeans.values().toArray()[0].getClass();
```

**Comment by roux-jerome** [comment]
RedisModulesConfiguration.ensureIndexesAreCreated` is invoked twice. The first one `ac.getBeansWithAnnotation(SpringBootApplication.class)` is empty. The second one is not

**Comment by DavidFischer1010** [comment]
See my Comment in the commit, this might be the cause. My previous fix has somehow regressed, I don't know the consequences of reverting this, since a lot has changed, so you might look into this @bsbodden.

The error occurs when I try to send an event via Spring Cloud Stream.

Best,
David

**Comment by daveish** [comment]
Oops, wrong account. This is the one... :D

**Comment by praks84** [comment]
I am stuck because of this issue - any workaround suggestions to get going till the fix?

**Comment by bsbodden** [comment]
Next release will have solve this issue. Likely out by Monday.

**Comment by bsbodden** [comment]
@praks84 @roux-jerome This should be fix in https://s01.oss.sonatype.org/content/repositories/snapshots/com/redis/om/redis-om-spring/0.6.2-SNAPSHOT/ a proper 0.6.2 release is pending
