### ISSUE TITLE
Document one-to-many support

### ISSUE THREAD

**Issue by xmlking** [redis/redis-om-spring#12]
I tried testing one-to-many relationship (embedded) with RedisJSON

**Person 1 -> * Address** is it supported ?

I see two anomalies in generated **FT.CREATE** 

1. `$.addresses[*]"`
2. `"$.email[*]" "AS" "email" "TAG" `  was expecting `"$.email" "AS" "email" "TAG"`

> ```1641669404.357554 [0 10.4.1.1:54854] "FT.CREATE" "PersonIdx" "ON" "JSON" "PREFIX" "1" "micro.apps.service.Person:" "SCORE_FIELD" "$.score" "SCHEMA" "$.name.first" "AS" "name_first" "TEXT" "$.name.last" "AS" "name_last" "TEXT" "$.addresses[*]" "AS" "addresses" "TAG" "$.email[*]" "AS" "email" "TAG"```

> ```1641669404.665621 [0 10.4.1.1:54854] "JSON.SET" "micro.apps.service.Person:01FRXHYAX2AVV8KH0FEK5MSWTX" "." "{\"score\":0.0,\"name\":{\"first\":\"sumo\",\"last\":\"demo\",\"title\":\"Sr\"},\"addresses\":[{\"suite\":\"222\",\"street\":\"fourt st\",\"city\":\"riverside\",\"state\":\"CA\",\"code\":\"95543\",\"country\":\"USA\",\"location\":\"-122.1245,47.64016\"}],\"gender\":\"MALE\",\"dob\":928047600000,\"email\":\"sumo@demo.com\",\"avatar\":\"https://www.gravatar.com/avatarr\"}"```

```kotlin
@Document("person")
data class Person(
    @Id val id: String? = null,
    @DocumentScore
    val score: Double,
    @Indexed
    val name: Name,
    @Indexed
    val addresses: Set<Address> = setOf(),
    val gender: Gender?,
    val dob: Date?,
    @Indexed
    @Bloom(name = "bf_person_email", capacity = 100000, errorRate = 0.001)
    var email: String,

    val phone: String? = null,
    val avatar: String = "https://www.gravatar.com/avatarr"
) {
    fun addAddress(address: Address) {
        (this.addresses as HashSet).add(address)
    }
}


data class Name(
    @Searchable
    val first: String?,
    @Searchable
    val last: String?,
    val title: String? = null
)


data class Address(
    @Id val id: String? = null,
    val suite: String? = null,
    @Searchable(nostem = true)
    val street: String,
    @Indexed
    val city: String,
    @Indexed
    val state: String,
    val code: String,
    @Indexed
    val country: String,
    @Indexed
   val location: Point? = null
)
```

**Comment by bsbodden** [comment]
See the new demo permits, specifically https://github.com/redis/redis-om-spring/blob/main/demos/roms-permits/src/main/java/com/redis/om/permits/models/Permit.java it has an Address 1-to-1 using `@Indexed` which then goes into the Address class looking for subfields containing `@Indexed`. I'll publish the 0.2.0 snapshot which should have that functionality, or you can just run the demo from this repo to try it

**Comment by bsbodden** [comment]
@xmlking I just pushed 0.2.0-SNAPSHOT, please give it a try following the roms-permits demo, see what you get. Thanks!

**Comment by xmlking** [comment]
with latest  `0.2.0-SNAPSHOT`  **email** and  **1-to-1** `Person-to-address` index is produced  as expected. 
I guess indexing on **1-to-many** `Person-to-addresses`  not possible due to RedisJSON limitation 
 
```kotlin
@Document("person")
data class Person(
    @Id val id: String? = null,
    @DocumentScore
    val score: Double,
    @Indexed
    val name: Name,
    @Indexed
    val addresses: Set<Address> = setOf(),
    @Indexed
    val address: Address?,
    val gender: Gender?,
    // @Serializable(with = DateAsLongSerializer::class) // @Polymorphic
    val dob: Date?,
    @Indexed
    @Bloom(name = "bf_person_email", capacity = 100000, errorRate = 0.001)
    var email: String,

    val phone: String? = null,
    val avatar: String = "https://www.gravatar.com/avatarr"
) {
    fun addAddress(address: Address) {
        (this.addresses as HashSet).add(address)
    }
}
```

```1641683366.251372 [0 10.4.1.1:37100] "FT.CREATE" "PersonIdx" "ON" "JSON" "PREFIX" "1" "micro.apps.service.Person:" "SCORE_FIELD" "$.score" "SCHEMA" "$.name.first" "AS" "name_first" "TEXT" "$.name.last" "AS" "name_last" "TEXT" "$.addresses[*]" "AS" "addresses" "TAG" "$.address.street" "AS" "address_street" "TEXT" "NOSTEM" "$.address.city" "AS" "address_city" "TAG" "$.address.state" "AS" "address_state" "TAG" "$.address.country" "AS" "address_country" "TAG" "$.address.location" "AS" "address_location" "GEO" "$.email" "AS" "email" "TAG"```

**Comment by xmlking** [comment]
is this still valid approach to convert `SearchResult` to  model i.e., `Person` ?


```kotlin
@RestController
@RequestMapping("/api/people")
class PersonController(private val personRepository: PersonRepository, private val modulesOperations: RedisModulesOperations<String, String>) {
    var ops = modulesOperations.opsForSearch("PersonIdx")
    private val gson: Gson = Gson()

    @GetMapping("title")
    fun findByTitle(@RequestParam title: String): Person? {
        val result: SearchResult = ops.search(Query("@address_city:'$title'"))
        if (result.totalResults > 0) {
            val doc: Document = result.docs[0]
            return gson.fromJson(doc.toString(), Person::class.java)
        } else return null
    }
}
```

I saw somewhere in you code `result.docs.get(0).get("$").toString()`  and a bit confused

**Comment by xmlking** [comment]
**not related ask:** may be in the future looking for options to use other JSON serializers beyond  **gson**.
for example we are using [kotlinx.serialization ](https://github.com/Kotlin/kotlinx.serialization) for our models

**Comment by bsbodden** [comment]
> ```kotlin
> SearchResult
> ```

For JSON searches you can use GSON to transform the payload to the target class. Not for @RediHash annotated models. For those you'll have to do something like https://github.com/redis/redis-om-spring/blob/main/redis-om-spring/src/main/java/com/redis/om/spring/repository/query/RedisEnhancedQuery.java#L230 which relies on https://github.com/redis/redis-om-spring/blob/main/redis-om-spring/src/main/java/com/redis/om/spring/repository/query/RedisEnhancedQuery.java#L239 

Although I plan to add a fluent query builder based on the Java Streams API that will make such maneuvers unnecessary.
