### ISSUE TITLE
About updateField() method

### ISSUE THREAD

**Issue by bwhyman** [redis/redis-om-spring#122]
I am trying to update field without retrieving the whole document by using updateField().

```java
User u = User.builder().number("test").password("test01").build();
User user2 = userRepository.save(u);
userRepository.updateField(user2, new TextTagField<User, String>(User.class.getDeclaredField("password"), true),  "101010");
```
When running the first time, the data can be saved and updated.
However, if running the same code, trying to save and update a new document again. I got this, the fully-qualified class name is missing.
```shell
"JSON.SET" "null01GGZDH1152DTNHGYP5X4Z23N9" "$.password" "\"101010\""

**Comment by bsbodden** [comment]
@bwhyman does it happen on the same running instance of the app, or is this on a restart?

**Comment by bwhyman** [comment]
springboot: 2.7.5
docker images: redis/redis-stack-server:7.0.2-RC3
FLUSHALL everytime for testing.

redis-om-spring:0.6.2
Monitor null even the FIRST time.
```shell
"JSON.SET" "null01GH0503GY7QDR1487N7F8NK6V" "$.password" "\"101010\""
```

redis-om-spring:0.6.0 && 0.6.1
Still, the first time is fine, but the second is not.
```shell
"JSON.SET" "null01GH05FVEYX5NVB8HCD2AZQVDC" "$.password" "\"101010\""
```

Testing in one unit testing, so it restarted everytime, that why it is very odd.
```java
@Test
    public void test2() throws NoSuchFieldException {
        User u = User.builder().number("test2").password("test02").build();
        User user2 = userRepository.save(u);
        userRepository.updateField(user2, new TextTagField<User, String>(User.class.getDeclaredField("password"), true),
                "101010");
    }
```
Hope it's helpful.

**Comment by bsbodden** [comment]
@bwhyman once this https://github.com/redis/redis-om-spring/pull/123 gets merged I think it should address the issue.

**Comment by bwhyman** [comment]
Thanks!~

**Comment by bsbodden** [comment]
@bwhyman could you clear your Maven cache and try the new deployment of 0.6.2-SNAPSHOT?

**Comment by bwhyman** [comment]
> @bwhyman could you clear your Maven cache and try the new deployment of 0.6.2-SNAPSHOT?

sorry, just saw it. 0.6.2-SNAPSHOT, works fine for me.
```java
User u = User.builder().id("01GH3WASQAKA3YEWQ7X6PAA4J5").password("002").build();
userRepository.updateField(u, new TextTagField<User, String>(User.class.getDeclaredField("password"), true),
                u.getPassword());
```
monitor 
```shell
 "JSON.SET" "com.example.redisjsonexamples.entity.User:01GH3WASQAKA3YEWQ7X6PAA4J5" "$.password" "\"002\""
```

Hover, if have encapsulated object
```java
User u = User.builder().name("SUN").address(Address.builder().detail("114").insertTime(LocalDateTime.now()).build()).build();
        userRepository.save(u);
```
and only want update user.address.detail, not include insertTime. It will cover the whole address object data.
```shell
"JSON.SET" "com.example.redisjsonexamples.entity.User:01GH3XCWKYWC1ECSHFTMKYGJ0S" "$.address" "\"555\""

json.get  "com.example.redisjsonexamples.entity.User:01GH3XCWKYWC1ECSHFTMKYGJ0S"
"{\"id\":\"01GH3XCWKYWC1ECSHFTMKYGJ0S\",\"name\":\"SUN\",\"address\":\"555\"}"
```
So, it seem like updateField(), update without retrieving the whole document, only work for ROOT property.

**Comment by bwhyman** [comment]
Actually, if @Modifying+@Query(spring-data) can be provided/implemented it will be very flexible.
```java
@Modifying
@Query("update user u set u.count=u.count+1 where u.total-u.count>0 and id=:tid")
Mono<Integer> updateTeacherCount(long tid);
```
