### ISSUE TITLE
Add limit/offset support to @Query

### ISSUE THREAD

**Issue by anyili** [redis/redis-om-spring#125]
The current `@Query` annotation only supports value and returnFields. By default redis search only return 10 results. Could we have support with limit filed in the `@Query` annotation?

**Comment by bsbodden** [comment]
@anyili You can use Spring's Pageable to accomplish that, like:

```
  /**
   * <pre>
   * > FT.SEARCH idx @title:hel* LIMIT 0 2
   * </pre>
   */
  @Query("@title:$prefix*")
  Page<MyDoc> customFindAllByTitleStartingWith(@Param("prefix") String prefix, Pageable pageable);
  ```

**Comment by anyili** [comment]
@bsbodden Hi Brian, I think my question is if you ave returnField in the Query, you can not have Pagable, which will only return 10 records from the redis

**Comment by bsbodden** [comment]
@anyili if you clear you Maven cache and pull down `0.6.3-SNAPSHOT` again I've implemented this feature, see sample usage:
* https://github.com/bsbodden/redis-om-spring/blob/bsb/moar-cleanup/redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/RedisDocumentSearchTest.java#L203
* https://github.com/bsbodden/redis-om-spring/blob/91f2c313bbacbc073ed457e0dd5d5475660c0042/redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/MyDocRepository.java#L72

**Comment by anyili** [comment]
@bsbodden Thanks for adding this feature, could we have `limit` refer to the parameter in the function signature. So we can call the repository by passing the limit dynamically?

**Comment by bsbodden** [comment]
Go ahead and create a new issue for it. That feature would likely have to be done with the `Pageable` APIs as to comply with the Spring Data method signatures.
