### ISSUE TITLE
Insufficient documentation for getIds() method in RedisDocumentRepository

### ISSUE THREAD

**Issue by sergey-morenets** [redis/redis-om-spring#126]
Hi

I tried to use this method in my repository:
```

public interface UserRepository 
		extends RedisDocumentRepository<User, Integer> {
```

`Iterator<Integer> iterator = repository.getIds().iterator();`

But received an exception:

```
java.lang.NullPointerException: Cannot invoke "String.endsWith(String)" because "keyspace" is null
	at com.redis.om.spring.RediSearchIndexer.getKey(RediSearchIndexer.java:512) ~[redis-om-spring-0.6.2.jar:na]
	at com.redis.om.spring.RediSearchIndexer.getIndexName(RediSearchIndexer.java:476) ~[redis-om-spring-0.6.2.jar:na]
	at com.redis.om.spring.repository.support.SimpleRedisDocumentRepository.getIds(SimpleRedisDocumentRepository.java:91) ~[redis-om-spring-0.6.2.jar:na]
```

Method itself doesn't have JavaDocs so it's not clear how and when to use it. So please JavaDocs or documentation in GitHub.

My User class:

```
@Getter
@Setter

@Document("users")
public class User {

	@Id
	private int id;

	private String name;

	private int age;

}
```

**Comment by sergey-morenets** [comment]
Also documentation is not correct for overloaded getIds() method:

```
@NoRepositoryBean
public interface RedisDocumentRepository<T, ID> extends KeyValueRepository<T, ID> {

  /**
   * Returns a {@link Page} of entities meeting the paging restriction provided in the {@code Pageable} object.
   *
   * @param pageable encapsulates pagination information
   * @return a page of entities
   */
  Page<ID> getIds(Pageable pageable);
```

It states that method returns entities but signature clearly shows that it return entity **identifiers**.

**Comment by bsbodden** [comment]
@sergey-morenets I think this should be resolved in https://s01.oss.sonatype.org/content/repositories/snapshots/com/redis/om/redis-om-spring/0.6.3-SNAPSHOT/

Could please try it? And thanks for the doc correction.

**Comment by sergey-morenets** [comment]
> @sergey-morenets I think this should be resolved in https://s01.oss.sonatype.org/content/repositories/snapshots/com/redis/om/redis-om-spring/0.6.3-SNAPSHOT/
> 
> Could please try it? And thanks for the doc correction.

Thank you. getIds() works correctly. Unfortunately there're no sources in this repository so I couldn't check the documentation update.
