### ISSUE TITLE
Redis TTL not working

### ISSUE THREAD

**Issue by shubham2705** [redis/redis-om-spring#129]
I have implemented RedisJSON using redis-om-spring on top of spring-data-redis. 

Using the following implementation
implementation 'com.redis.om:redis-om-spring:0.6.2'

My model looks as follows
@Data
@Document(value = "user", timeToLive = 60 * 60)
public class UserDto {

	@Id
	@Indexed
	private String userId;
	private String name;
	private boolean isActive;
	private String dept;
}
However, the timeToLive specified is not working at the moment. the data is saved in redis with infinite TTL.
Is there any other way to define TTL for this, or it is not working.

**Comment by bsbodden** [comment]
Should be resolved in https://s01.oss.sonatype.org/content/repositories/snapshots/com/redis/om/redis-om-spring/0.6.3-SNAPSHOT/

Could please try it?

**Comment by shubham2705** [comment]
@bsbodden I tried it with the above mentioned snapshot and it is working successfully. Now we are getting the required ttl specified. Thanks for quick resolution. 
Also, let me know when you are planning to release this change.

**Comment by bsbodden** [comment]
We'll probably pack a few more bug fixes and tests and release on Monday/Tuesday
