### ISSUE TITLE
How to set Language when execute search?

### ISSUE THREAD

**Issue by leeaee** [redis/redis-om-spring#139]
When create the FT.CREATE, it could set the LANGUAGE parameter when define the language in @Document, but when FT.SEARCH, it could not add the LANGUAGE parameter.
So, how to pass the language when the RedisDocumentRepository not auto added?

**Comment by bsbodden** [comment]
You are correct, there is no way to pass the language parameter at this moment. I will add one in the next couple of days. Likely it will be in the next minor release. Good catch!

**Comment by bsbodden** [comment]
This has been implemented, it will be available in the next release
