### ISSUE TITLE
Question - Is it possible to filter entity stream by a nested field property ? 

### ISSUE THREAD

**Issue by reemdiab** [redis/redis-om-spring#140]
public class Parent {
          private String id;
          private Child child;
}

public class Child {
          private String id;
          private Long score;
}

List<Parent> parentList = entityStream
                .of(Parent.class)
                .filter(Parent$.CHILD_SCORE.gt(5)) ???? something similar to this ???? 
                .collect(Collectors.toList())
                
   Thanks

**Comment by bsbodden** [comment]
@reemdiab not currently, I'm working on a way to do the nesting in clean fashion, stay tuned. I'll post a work around here later this week.

**Comment by reemdiab** [comment]
Also is it possible to do full text search in stream ? as one of the filters ?
Thanks

**Comment by bsbodden** [comment]
Yes, there is a new `.filter(String expression)` to do so. It should be in the next release.
