### ISSUE TITLE
[Bug] RediSearchIndexer.createIndexFor method use hardcoded entity prefix as class name making RedisMappingContext and FallbackKeySpaceResolver unusable.

### ISSUE THREAD

**Issue by setu9760** [redis/redis-om-spring#142]
spring-data-redis allows to define custom `RedisMappingContext` bean with configurable `fallbackKeySpaceResolver`; this is useful when the requirement is to prefix/suffix every redis key with some custom value e.g. environment/service name in shared redis instance. This can be configured as below bean definition;

```java
  @Bean
  @Primary
  public RedisMappingContext keyValueMappingContext(
      @Value(value = "${redis.custom.keyspace.prefix}") String keyspacePrefix) {
    RedisMappingContext mappingContext = new RedisMappingContext();
    mappingContext.setFallbackKeySpaceResolver(type -> keyspacePrefix + ":" + type.getSimpleName());
    return mappingContext;
  }
```

What this bean is supposed to do is every spring-data-redis operation will use fallback keyspace response and prefix the keyspace with some configurable value. As an example if we are trying to store/lookup com.example.Company entity instead of the key being `com.example.Company:ID1` it would be `<prefix>:Company:ID1`.

This works for standard spring-data-redis however not for redis-om-spring. I did some investigation and to me this looks like a bug with `RediSearchIndexer.createIndexFor(class)` method. It has hardcoded logic to always use entity classname as prefix in json schema creation. `RediSearchIndexer` already has an instance of `RedisMappingContext` and straightforward fix for this would be to add the following lines for entityPrefix logic;

```java
      String entityPrefix = cl.getName() + ":";
      if (mappingContext.hasPersistentEntityFor(cl)) {
        RedisPersistentEntity<?> persistentEntity = mappingContext.getRequiredPersistentEntity(cl);
        entityPrefix = persistentEntity.getKeySpace() != null ? persistentEntity.getKeySpace() + ":" : entityPrefix;
      }
```

I have created reproducible example in [this repository](https://github.com/setu9760/redis-om-custom-keyspace). I am happy to get inputs on this and also contribute the fix if agreed.

**Comment by bsbodden** [comment]
A PR will be most welcomed!

**Comment by setu9760** [comment]
Ok I will apply the fix and open PR
