### ISSUE TITLE
SpringBoot3.0 support？

### ISSUE THREAD

**Issue by thezhuling** [redis/redis-om-spring#144]
java17 and SpringBoot3.0 support feature？

**Comment by bsbodden** [comment]
It's coming... ~January 15th or so.

**Comment by dashaun** [comment]
Will that also include native-image support?

**Comment by bsbodden** [comment]
@dashaun Is there a guide for making libraries native-ready? I could use some help!

**Comment by bsbodden** [comment]
The PR is being reviewed!

**Comment by bsbodden** [comment]
It's in main branch, release is coming soon

**Comment by bsbodden** [comment]
SNAPSHOT release here => https://s01.oss.sonatype.org/content/repositories/snapshots/com/redis/om/redis-om-spring/0.8.0-SNAPSHOT/
