### ISSUE TITLE
JSON Repository No SUB Index of type NUMBER

### ISSUE THREAD

**Issue by fr4ncesco** [redis/redis-om-spring#147]
When try to index referenced classed the Library only crete index of type `TEXT`. `NUMBER` and `TAG` seems not present.
Following a basic example.
If you try to map the following class:

```java
@Data
@RequiredArgsConstructor(staticName = "of")
@AllArgsConstructor(access = AccessLevel.PROTECTED)
@Document
public class Company {
    @Id
    private String id;

    @NonNull
    @Searchable
    private String name;

    @Indexed
    @NonNull 
    private Integer numberOfEmployees;

    @NonNull
    @Indexed
    private Set<CompanyMeta> metaList;
}

@Data
@RequiredArgsConstructor(staticName = "of")
@Document
public class CompanyMeta {
    
    @Indexed
    @NonNull
    private String name;

    @Indexed
    @NonNull
    private String value;

    @Indexed
    @NonNull 
    private Integer numberOfEmployees;
}
```

The library creates an index in the following way (copied using the client monitor):
```
"FT.CREATE" "com.synapseslab.example.redisjson.domain.CompanyIdx" "ON" "JSON" "PREFIX" "1" "com.synapseslab.example.redisjson.domain.Company:" "SCHEMA" "$.name" "AS" "name" "TEXT" "$.numberOfEmployees" "AS" "numberOfEmployees" "NUMERIC" "$.metaList[0:].name" "AS" "metaList_name" "TAG" "SEPARATOR" "|" "$.metaList[0:].value" "AS" "metaList_value" "TAG" "SEPARATOR" "|" "$.id" "AS" "id" "TAG" "SEPARATOR" ","
```

Need to have also an index like the following:
`"$.metaList[0:].numberOfEmployees" AS metalList_numberOfEmployees NUMERIC`

Same for type TAG. Seems only the TEXT index is supported.

**Comment by bsbodden** [comment]
The one issue I see above is the extra `@Document` in `CompanyMeta`, since child/many-to-one objects with Redis JSON are just embedded in the document and not referenced. But, that wouldn't likely cause the issue above. Can you post a full example? I'll play with it tonight and see if I can figure it out. Cheers!

**Comment by fr4ncesco** [comment]
Hello Brian,
thanks for the feedback in attach the full example, it is just a test project made with with Spring Boot.

Anyhow I have to amend my previous. The problem is present only for type `NUMBER` the type `TAG` works as expected.


[redisjson.zip](https://github.com/redis/redis-om-spring/files/10399174/redisjson.zip)

**Comment by fr4ncesco** [comment]
Hi Brian,
I download the repo and try to fix it on the example.

In attach the project with the fix.

I'm not sure this is the beast approach but it works.

If needed I can push a branch with the fix.

The mdofication affect the class RedisSearchIndexer

```java
 } else if (subField.isAnnotationPresent(Indexed.class)) {
          boolean subFieldIsTagField = ((subField.isAnnotationPresent(Indexed.class)
              && ((CharSequence.class.isAssignableFrom(subField.getType()) || (subField.getType() == Boolean.class)
                  || (maybeCollectionType.isPresent() && (CharSequence.class.isAssignableFrom(maybeCollectionType.get())
                      || (maybeCollectionType.get() == Boolean.class)))))));
          if (subFieldIsTagField) {
            Indexed indexed = subField.getAnnotation(Indexed.class);
            tempPrefix = field.getName() + "[0:].";

            FieldName fieldName = FieldName.of(fieldPrefix + tempPrefix + subField.getName());
            fieldName = fieldName.as(QueryUtils.searchIndexFieldAliasFor(subField, prefix));

            logger.info(String.format("Creating nested relationships: %s -> %s", field.getName(), subField.getName()));
            fieldList.add(new TagField(fieldName, indexed.separator(), false));
            continue;
          }

          else if (Number.class.isAssignableFrom(subField.getType()) || (subField.getType() == LocalDateTime.class)
              || (subField.getType() == LocalDate.class) || (subField.getType() == Date.class)) {

            FieldName fieldName = FieldName.of(fieldPrefix + tempPrefix + subField.getName());
            fieldName = fieldName.as(QueryUtils.searchIndexFieldAliasFor(subField, prefix));
            logger.info(String.format("Creating nested relationships: %s -> %s", field.getName(), subField.getName()));
            fieldList.add(new Field(fieldName, FieldType.Numeric));
          }
        }

        getNestedField(fieldPrefix + tempPrefix, subField, prefix, fieldList);
}
```
I added the else if with Number.class checks to line 493.

In the attach there is also the example for the meta subfield.


[redis-om-spring.zip](https://github.com/redis/redis-om-spring/files/10399705/redis-om-spring.zip)

**Comment by bsbodden** [comment]
@fr4ncesco this is great. Why don't you send a formal PR, would love to have you as a contributor!

**Comment by bsbodden** [comment]
Thanks @fr4ncesco merged and implemented the required repository queries
