### ISSUE TITLE
can't run in JDK 8 ?

### ISSUE THREAD

**Issue by Cherry-Ran** [redis/redis-om-spring#15]
most of JAVA developer are use JDK8 version in China,and have you plan for adaptation JDK 8 ?

**Comment by bsbodden** [comment]
There are no current plans for JDK8 support at the moment, once we get the code base to a 1.0 release we'll re-evaluate.

**Comment by georgejdli** [comment]
so based on this comment https://github.com/redis/redis-om-spring/issues/171#issuecomment-1412738333
this project has no plans for adding support for Java 8 in a 1.0 release?
