### ISSUE TITLE
Adding a new attribute to an existing index

### ISSUE THREAD

**Issue by reemdiab** [redis/redis-om-spring#163]
Hi,
I tried to add a new attribute to an existing @Document annotated class.
And i see the schema in redis was not updated.

Do you have anyway i can refresh the index creation if there is a change ?

Thanks

**Comment by bsbodden** [comment]
Not at the moment. I'm planning on a migrations API similar to Rails Migrations, see https://github.com/redis/redis-om-spring/issues/26

**Comment by reemdiab** [comment]
Thanks
