### ISSUE TITLE
firstName or lastName contains hyphen

### ISSUE THREAD

**Issue by cscan** [redis/redis-om-spring#167]
I put the hyphen in the firstName of lastName, like this
```
personRepo.save( Person.of("Demon-Hunter", "Golin", "test@redis.com") );
```

but it cannot be searched by the same string, i.e.
```
personRepo.findByLastNameAndFirstName("Golin", "Demon-Hunter");
```
Note that there is no problem if I use dot or other char. Hyphen is reserved? or anything I was wrong?

**Comment by bsbodden** [comment]
You might need to escape the hyphen during searching:

```java
personRepo.findByLastNameAndFirstName("Golin", "Demon\\-Hunter");
```
