### ISSUE TITLE
Annotation Processor does not appear to be invoked

### ISSUE THREAD

**Issue by abiri-1mrobotics** [redis/redis-om-spring#173]
We are using the library and everything seems to be working expect the meta model generation.

I suspect it's due to this:

```
@SupportedAnnotationTypes("com.redis.om.spring.annotations.Document")
@SupportedSourceVersion(SourceVersion.RELEASE_11)
@AutoService(Processor.class)
public final class MetamodelGenerator extends AbstractProcessor {
```

Is the generator limited to Java 11 projects?

We're using Gradle and Kotlin with Java 17, but while trying to diagnose the problem we created one Java Pojo to test. As far as we can tell the meta model generator either isn't running or is not picking up the Pojo class.

```
# Person.java
import com.redis.om.spring.annotations.Document;
import com.redis.om.spring.annotations.Searchable;
import org.springframework.data.annotation.Id;

@Document
public class Person {
    @Id
    private String id;
    @Searchable
    private String name;

    ... // Getters and setters (No Lombok in project)
}
```

```
# build.gradle.kts

plugins {
    kotlin("jvm")
    kotlin("kapt")
}

dependencies {
    annotationProcessor("com.redis.om:redis-om-spring:0.6.4")
    kapt("com.redis.om:redis-om-spring:0.6.4")
    implementation("com.redis.om:redis-om-spring:0.6.4")
}
```

We are not seeing anything in the `build/.../generated` folder and cannot resolve `Person$` in the project.

Are we doing something wrong or is it simply that Java 17 is not supported yet?

**Comment by bsbodden** [comment]
Can you post your Gradle build?

**Comment by bsbodden** [comment]
And make sure that you include the dependency as:

```groovy
ext {
  redisOmVersion = '0.8.0-SNAPSHOT'
}

dependencies {
    implementation: "com.redis.om:redis-om-spring:$redisOmVersion"
    }
}
```

**Comment by abiri-1mrobotics** [comment]
Hi - I have no idea why but it suddenly started working!

Closing. Sorry for wasting time... :-)

**Comment by rjdkolb** [comment]
@abiri-1mrobotics ,are you using other annotation processors as well?
I had an issue with Maven and Java which I have a solution for. I was using Lombok and QueryDSL as well.
