### ISSUE TITLE
Feature Request: Support Kotlin immutable data classes

### ISSUE THREAD

**Issue by abiri-1mrobotics** [redis/redis-om-spring#174]
Maybe this isn't related to Kotlin but to support for immutable Pojos in general. However we're encountering it from a Kotlin perspective:

So right now this will work in Kotlin:

```
@Document
data class CachedProducts(
    @Id
    @Indexed
    var id: String,
    @Indexed
    var firstName: String,
    @Indexed
    var lastName: String,
)
```

But in Kotlin it's idiomatic to aim for immutable models:

```
@Document
data class CachedProducts(
    @Id
    @Indexed
    val id: String,
    @Indexed
    val firstName: String,
    @Indexed
    val lastName: String,
)
```

However that hides the properties from the generator and results in an exception.

**Comment by bsbodden** [comment]
You're right, we haven't yet dealt with immutable POJOs. I'm aiming to have this in place before we reach 1.0.0

**Comment by abiri-1mrobotics** [comment]
I'm sure you're aware of this, but for any future pre-1.0.0 time travellers - this also applies to Java/Lombok immutable Pojos / records:

```
@Document
@Getter
public class Person {
    @Id
    private final String id;

    @Indexed
    private final String firstName;

    @Indexed
    private final String lastName;

    @Indexed
    private final List<Address> addresses;

    public Person(String id, String firstName, String lastName, List<Address> addresses) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.addresses = addresses;
    }
}
```

```
@Document
public record Person(
    @Id String id,
    @Indexed String firstName,
    @Indexed String lastName,
    @Indexed List<Address> addresses
) { }
```

In particular `record`s are not picked up at all by the generator.

**Comment by bsbodden** [comment]
Indeed, we have another issue open to support Records

**Comment by bsbodden** [comment]
@abiri-1mrobotics See https://github.com/redis/redis-om-spring/issues/21 , unfortunately same applies here
