### ISSUE TITLE
entity search order for text effects underlying query.

### ISSUE THREAD

**Issue by rjdkolb** [redis/redis-om-spring#176]
maven version: 0.6.4

If you search for on a field first and on then on free text, the field part of the query is dropped.

So this does not work as it returns data not for **Microsoft**:

```
var result3 = entityStream.of(Company.class)
      .filter(Company$.NAME.eq("Microsoft"))
      .filter("*co*")
      .collect(Collectors.toList());
System.out.println("Search3:");
```

This works:

```
var result4 = entityStream.of(Company.class)
        .filter("*net*")
        .filter(Company$.NAME.eq("Microsoft"))
        .collect(Collectors.toList());
System.out.println("Search4:");
result4.forEach(System.out::println);
```

I found this when I was looking in JRediSearch [io.redisearch.client.Client](https://github.com/RediSearch/JRediSearch/blob/v2.2.0/src/main/java/io/redisearch/client/Client.java#L374)

My data based on the [roms-documents](https://github.com/redis/redis-om-spring/tree/v0.6.4), I modified [RomsDocumentsApplication](https://github.com/redis/redis-om-spring/blob/v0.6.4/demos/roms-documents/src/main/java/com/redis/om/documents/RomsDocumentsApplication.java)
```
companyRepo.deleteAll();
Company redis1 = Company.of("Redis", "wwwabccom", new Point(-122.066540, 37.377690), 526, 2011, Set.of(CompanyMeta.of("Redis", 100, Set.of("RedisTag"))));
Company redis2 = Company.of("Redis", "wwwxyzcom", new Point(-122.066540, 37.377690), 526, 2011, Set.of(CompanyMeta.of("Redis", 100, Set.of("RedisTag"))));

Company microsoft1 = Company.of("Microsoft", "wwwabcnet", new Point(-122.066540, 37.377690), 526, 2011, Set.of(CompanyMeta.of("Redis", 100, Set.of("RedisTag"))));
Company microsoft2 = Company.of("Microsoft", "wwwxyznet", new Point(-122.066540, 37.377690), 526, 2011, Set.of(CompanyMeta.of("Redis", 100, Set.of("RedisTag"))));


companyRepo.save(redis1);
companyRepo.save(redis2);
companyRepo.save(microsoft1);
companyRepo.save(microsoft2);
```

[Stackoverflow question](https://stackoverflow.com/questions/75299609/how-to-search-for-text-and-filter/75334188#75334188).

**Comment by bsbodden** [comment]
Thanks @rjdkolb! Currently investigating. Can you do me a favor and capture the commands that are being sent to Redis by running the Redis CLI is monitor mode? `redis-cli MONITOR`?

**Comment by rjdkolb** [comment]
Pleasure :)

For Search3 I get:

`1675437670.689313 [0 172.17.0.1:60888] "FT.SEARCH" "com.redis.om.documents.domain.CompanyIdx" "*co*" "LIMIT" "0" "10000"`

For Search 4 I get:

`1675437762.647725 [0 172.17.0.1:60890] "FT.SEARCH" "com.redis.om.documents.domain.CompanyIdx" "(*co* @name:{Microsoft})" "LIMIT" "0" "10000"`

**Comment by bsbodden** [comment]
Looks like a bug!

**Comment by setu9760** [comment]
@bsbodden If you haven't already found the fix; may I contribute for this one please?

**Comment by rjdkolb** [comment]
@setu9760 , I am happy to verify the fix. :)

**Comment by bsbodden** [comment]
@setu9760 and @rjdkolb please! It was on my current list but haven't gotten to it yet! Thank you!

**Comment by bsbodden** [comment]
@rjdkolb FYI    the chaining of filters implies and "AND" so on the search above you should get no results based on the sample data. For an "OR" you can do:

```java
    List<Company> companies = stream //
        .filter( //
            Company$.NAME.eq("RedisInc") //
                .or(Company$.NAME.eq("Microsoft")) //
        ) //
        .collect(Collectors.toList());
``` 

@setu9760 if you haven't figure out a fix, I have simple one.

**Comment by rjdkolb** [comment]
thanks @bsbodden , I saw there was a copy and paste error with my example. I updated search4.

```
var result4 = entityStream.of(Company.class)
        .filter("*net*")
        .filter(Company$.NAME.eq("Microsoft"))
        .collect(Collectors.toList());
System.out.println("Search4:");
result4.forEach(System.out::println);
```

Both _Search3_ and _Search4_ examples work correctly now.
