### ISSUE TITLE
redis host

### ISSUE THREAD

**Issue by cscan** [redis/redis-om-spring#183]
Hi, if I am not using composer to start up, and my redis stack server is not in localhost:6379. Where can I config to use another host? e.g. anotherhost:6379.

I have tried MAVEN_OPTS="-Dspring.redis.host=anotherhost" but no luck at all.

**Comment by rjdkolb** [comment]
Hi @cscan 

If I understand you correctly, all you need to do it setup a JedisConnectionFactory.

This is what I do:

```
@Configuration
public class RedisConfiguration {

    @Value("${spring.redis.host}")
    private String redisHost;

    @Value("${spring.redis.port:6379}")
    private Integer redisPort;
    @Bean
    public JedisConnectionFactory getJedisConnectionFactory(){
        return new JedisConnectionFactory(new RedisStandaloneConfiguration(redisHost, redisPort));
    }
}
```

In your application.yml

```
spring:
  redis:
      password: somepassword
      host: localhost
```

**Comment by bsbodden** [comment]
How are you starting the app? Typically just the traditional `application.properties` with:

```
spring.redis.host=xxx.xxx.xxx.xxx
spring.redis.port=86753
```

But what @rjdkolb posted should work if the regular app props does not.

**Comment by cscan** [comment]
@bsbodden I tried the old version, the application.properties works. But for the current version, it raises the exception when compile:
```
Caused by: java.lang.IllegalArgumentException: newPosition < 0: (-1 < 0)
```

**Comment by bsbodden** [comment]
> @bsbodden I tried the old version, the application.properties works. But for the current version, it raises the exception when compile:
> 
> ```
> Caused by: java.lang.IllegalArgumentException: newPosition < 0: (-1 < 0)
> ```

Can you open an issue for it? Thanks!
