### ISSUE TITLE
Search on Spaces with asterisk return 0 results

### ISSUE THREAD

**Issue by virgiliosanz** [redis/redis-om-spring#184]
Hi,

I have created a repo to reproduce the issue at: https://github.com/virgiliosanz/redis_search_spaces
You will need a redis-stack server in the same machine at the standard port with no password in order to make it work.
The query doesn't also work using redis-cli:

![image](https://user-images.githubusercontent.com/266326/218146153-1c5e9c51-7543-4af5-87cc-40ab33535934.png)

Regards,
v

**Comment by bsbodden** [comment]
@virgiliosanz can you try this on your tester app?
