### ISSUE TITLE
Is there any way to simulate select field1, field2, field3 ... from person

### ISSUE THREAD

**Issue by cscan** [redis/redis-om-spring#188]
In repository:
```
Optional<Company> findOneByName(String name);
```
I know that it will retrieve the whole model "Company" from redis cache.

Is there any way (i.e. specified annotation in model) to retrieve some fields instead of all fields? My case is our model is very big (over 200 fields), we only interested in part of the model (5 fields only). I believe it will be speed up in serialisation if the number of fields are smaller.

**Comment by cscan** [comment]
json.mget may work

**Comment by bsbodden** [comment]
Not with repositories but you can with the EntityStreams API see the tests in https://github.com/redis/redis-om-spring/tree/main/redis-om-spring/src/test/java/com/redis/om/spring/search/stream
