### ISSUE TITLE
TagField does not implement startsWith

### ISSUE THREAD

**Issue by nerg4l** [redis/redis-om-spring#189]
> Tags support prefix matching with the regular * character:
>
> ```
> FT.SEARCH idx "@tags:{ hell* }"
> FT.SEARCH idx "@tags:{ hello\\ w* }"
> ```

https://redis.io/docs/stack/search/reference/tags/#querying-tag-fields

Unfortunately, the current `TagField` implementation does not implement `startsWith` method which would add prefix-matching functionality.

Is there a workaround other than a custom `Predicate` which could be used until this feature is added?

**Comment by bsbodden** [comment]
I'm on it! Earlier on TAG fields were a bit more limited.
