### ISSUE TITLE
Backport 0.8.0 features to 0.7.X branch

### ISSUE THREAD

**Issue by bsbodden** [redis/redis-om-spring#194]

**Comment by rjdkolb** [comment]
I don't want to be that guy that asks when this will be released...
But any idea when this will be back ported?

We are still on Springboot 2.

Thanks

**Comment by bsbodden** [comment]
Next release should be out next week

**Comment by zUniQueX** [comment]
> Next release should be out next week

Like @rjdkolb I don't want to make pressure. May I ask, if there's a new ETA for the release?

**Comment by bsbodden** [comment]
Sorry guys, I've been over tasked, I'll focus on the backport next week

**Comment by zUniQueX** [comment]
@bsbodden Are there any plans for a release date of 0.7.0? We're currently using a manually deployed version but would appreciate an official release.

**Comment by rjdkolb** [comment]
@zUniQueX, we had a lot of Hibernate types that forced us to stay on Springboot 2, but we finally did the upgrade and it seems really worth it. Both on the Spring side and redis-om-spring sides.

I just used [OpenRewrite Recipe](https://docs.openrewrite.org/recipes/java/spring/boot3/upgradespringboot_3_0) to do most of the grunt work.

**Comment by bsbodden** [comment]
@rjdkolb Richard, that's great! I've been playing catchup with what the demands for 1.0 are and backporting to Spring 2.x. We'll likely not do so unless there is more demand. Hoping to have a fully featured 1.0 by EOY that is as bullet proof as it can be! Thanks for sticking around!

**Comment by zUniQueX** [comment]
@rjdkolb The problem isn't migrating a single project to Spring Boor 3 but to upgrade all libraries first.

If only one library in the infrastructure doesn't support SB3, the upgrade cannot be performed yet.
