### ISSUE TITLE
Indexed fields from superclasses

### ISSUE THREAD

**Issue by michaelstiller78** [redis/redis-om-spring#203]
Hi everyone,

in some of our projects we use redis-om-spring (version 0.6.4) to store our data in a redis stack container. We "converted" those projects from using spring-data-redis. Most of the conversions went fine, but in one project we ran into a problem.

The classes we want to store (which are annotated with "Document") all inherit from one abstract superclass. This superclass contains the "Id"-Field and all "Indexed"-fields. The "RediSearchIndexer" can/does not create the indices "because Fields arguments are missing".

As far as i understand the cause of this problem might be a specific loop in method "createIndexFor": for (java.lang.reflect.Field field : cl.getDeclaredFields())

Since "getDeclaredFields" is used instead of "getFields", fields of superclasses are "excluded" (as far as i understand).

Would you please provide support for Id, Indexed and Searchable fields in superclasses.

Regards

Michael

**Comment by bsbodden** [comment]
@zUniQueX so this in on main but will have to be backported to 0.7.x, I have a backlog for backporting.

**Comment by zUniQueX** [comment]
@bsbodden I don't know, if I understand you correctly here. Shall I backport this change (and maybe my other PRs) or will you do this?

**Comment by bsbodden** [comment]
> @bsbodden I don't know, if I correctly understand you here. Shall I backport this change (and maybe my other PRs) or will you do this?

If you have the cycles to do so, that'll be great. I have a long list to work off, so any help will be appreciated.

**Comment by zUniQueX** [comment]
> If you have the cycles to do so, that'll be great. I have a long list to work off, so any help will be appreciated.

I've just opened #223.

Looks like one test is flaky. However, it was so before.

**Comment by bsbodden** [comment]
> > If you have the cycles to do so, that'll be great. I have a long list to work off, so any help will be appreciated.
> 
> I've just opened #223.
> 
> Looks like one test is flaky. However, it was so before.

Which test is it? I had that was flaky but hasn't given me issues lately.

**Comment by zUniQueX** [comment]
> > > If you have the cycles to do so, that'll be great. I have a long list to work off, so any help will be appreciated.
> > 
> > I've just opened #223.
> > 
> > Looks like one test is flaky. However, it was so before.
> 
> Which test is it? I had that was flaky but hasn't given me issues lately.

IIRC there were three unstable test cases in the `OpsForSearchTest`.
