### ISSUE TITLE
Spring Webflux version

### ISSUE THREAD

**Issue by uuhnaut69** [redis/redis-om-spring#205]
Does this project will support spring webflux version ?

**Comment by bsbodden** [comment]
It should, this is just a Spring Data project, so if Spring Data Redis works with WebFlux, so should Redis OM Spring, try it, if it doesn't please report back and we'll troubleshoot.

**Comment by bsbodden** [comment]
BTW, version 0.8.0 required Spring 3 or greater

**Comment by uuhnaut69** [comment]
@bsbodden Thanks for your answers
