### ISSUE TITLE
Aggregation with EntityStream calls two requests

### ISSUE THREAD

**Issue by justTimTim** [redis/redis-om-spring#209]
When calling the aggregation functions through the EntityStream, first a 10,000 row search is performed, and then a second query with the aggregation. The "close" method from a Stream is a terminal operation, it calls stream. We haven't to ctually close an EntityStream if we need an aggregation because it's just an object that will be garbage collected.

**Comment by rasrov** [comment]
Hi @justTimTim!

Can you show me some example about how you building an Aggregation queries with Redis OM Spring library please?

I tried to find some examples and information, but I don't found nothing :/
