### ISSUE TITLE
How to save _class with RedisDocumentRepository

### ISSUE THREAD

**Issue by GeoffreyBourboin** [redis/redis-om-spring#218]
Hi, I wish to know how to save _class in my json when I use save from RedisDocumentRepository.
By default, I think spring data redis save it.

**Comment by bsbodden** [comment]
We might add this via a configuration option. What's your use case? I haven't found a real use for the `_class` field so far.

**Comment by GeoffreyBourboin** [comment]
My use case is as follows. I need to deserialize child classes that inherit from abstract parent class, a typical case of polymorphism.
I found a way to do this through adapters by overriding the serialization and deserialization methods and using the JsonSubType annotation.
So actually, I don't think it's a real need in my case. Adding the _class might avoid overriding the serialization and deserialization methods through adapters.
