### ISSUE TITLE
Specify DIALECT argument into EntityStream

### ISSUE THREAD

**Issue by rasrov** [redis/redis-om-spring#219]
Hi!

It's possible specify `DIALECT 2` argument into `EntityStream` class when I am building query with it?

`entityStream.of(RoadStatusEventVO.class).filter(RoadStatusEventVO$.INCIDENT_TYPE.eq(incidentType))
        .collect(Collectors.toList());`

I saw this example in other issue, but it's building an own query:

`Query q = new Query("*=>[KNN $K @my_vector $BLOB]").setSortBy("__my_vector_score", true).addParam("K", K).addParam("BLOB", floatToByte(e)).limit(0,K).dialect(2);`

**Comment by bsbodden** [comment]
Sounds reasonable... I was hoping that the query language will settle to the point of not needing to expose the users to "dialects" but it that doesn't seem to be the case, so I'll add it as a method.

**Comment by rasrov** [comment]
@bsbodden 
Thanks for your quick response!

I exposed this issue and example here
https://github.com/RediSearch/RediSearch/issues/3497

**Comment by rasrov** [comment]
Hi again @bsbodden !

I found info about stop words to not need use dialect on queries.

https://redis.io/docs/stack/search/reference/stopwords/
