### ISSUE TITLE
Fail setting TTL from property during save operation

### ISSUE THREAD

**Issue by rasrov** [redis/redis-om-spring#236]
Hi!

I'm trying to add an EXPIRETIME through the POJOs annotated with redis Data anotation, but I'm not seeing a way. I have seen that the @RedisHash annotation exists, but only timeToLive() can be specified.

What I want to achieve is that through a cron in my java microservice, every time the redis records are consumed, they are deleted.

I'm consuming data from index by aggregation. Cause of that, I can't use GETDEL command to solve this issue.

**Comment by bsbodden** [comment]
Are you trying to set a specific clock time for the entity to expire? See this StackOverflow for what is possible from Spring Data Redis https://stackoverflow.com/questions/42577222/spring-data-redis-global-ttl-for-all-entities

On top of what is built-in from SDR I had a method in the repositories to read the TTL by ID `Long getExpiration(ID id);`

I could add a setter for the TTL by ID but I first want to understand your use case, can you add some pseudo code

**Comment by rasrov** [comment]
What I'm trying to achieve is to specify how long a record is going to be alive for. 

Ie:
If the record is checked into redis at 10.41am, I want that record to expire at 10.45. So, I want to set the lifetime dynamically.

I have seen that this can be done with an annotation at the attribute level of type Long (`@TimeToLive`), instead of at the class level (`RedisHash(timeToLive = 120L`).

This is what I have tried to do, but following the trace, I have seen that it is not applying the corresponding time due to an error that `ReflectionUtils` is giving:

```java
Class RedisJSONKeyValueAdapter.java:213
Long ttlPropertyValue = ((Number)ReflectionUtils.invokeMethod(ttlGetter, entity)).longValue();
```

I'm trying to figure out why, but I can't.

The values ​​that arrive to the method, from my point of view, are correct.

The parameters of the invokeMethod method are these:

```java
ttlGetter = "public java.lang.Long com.disid.incidentpreprocessor.model.RoadStatusEventVO.getExpirationInSeconds()"
```

entity =
```java
RoadStatusEventVO
{
  eventId: "a2d83bf8-e562-41f5-9815-1267e8ba4fe3"
  severity: "HIGH"
  disease: "Road"
  ...
  expirationInSeconds@Long: 300
}
```

RoadStatusEventVO definition:
```java
@RequiredArgsConstructor(staticName = "of")
@Document(timeToLive = 150L) (Setted just for follow the trace)
@AllArgsConstructor
@NoArgsConstructor
public class RoadStatusEventVO {
  @Id @Indexed private String eventId;

  @Indexed @NonNull private String severity;

  @Indexed @NonNull private String disease;

  ...

  @TimeToLive(unit = TimeUnit.MINUTES) private Long expirationInSeconds = 300L (300L it's just for testing if it works);
}
```

**Comment by bsbodden** [comment]
Excellent, that gives me a really big start on fixing this. Thanks.

**Comment by bsbodden** [comment]
@rasrov I wanted to confirm that your intention is for `RoadStatusEventVO` to be mapped as a Redis Hash with `@RedisHash` and not as JSON with `@Document`, correct?

**Comment by rasrov** [comment]
Hii @bsbodden!

In my case I am mapping it as JSON, but I think it does not make any difference to me.

**Comment by bsbodden** [comment]
Here's the example from the tests that is working:

### Model

```java
package com.redis.om.spring.annotations.document.fixtures;

import com.redis.om.spring.annotations.Document;
import com.redis.om.spring.annotations.Indexed;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.redis.core.TimeToLive;

@Data
@NoArgsConstructor(force = true)
@RequiredArgsConstructor(staticName = "of")
@Document(timeToLive = 5)
public class ExpiringPerson {
  @Id String id;
  @NonNull @Indexed
  String name;
  
  @NonNull
  @TimeToLive Long ttl;
}
```

### Repo

Nothing TTL-realted needed here:

```java
@SuppressWarnings("unused") public interface ExpiringPersonRepository extends RedisDocumentRepository<ExpiringPerson, String> {
  Optional<ExpiringPerson> findOneByName(String name);
}
```

### Test

Relevant tests:

```java
  @Test
  void testTimeToLiveAnnotation() {
    ExpiringPerson mWoodger = ExpiringPerson.of("Mike Woodger", 15L);
    withTTLAnnotationRepository.save(mWoodger);

    Long expire = withTTLAnnotationRepository.getExpiration(mWoodger.getId());

    assertThat(expire).isEqualTo(15L);
  }
  
  @Test
  void testTimeToLiveAnnotationWithDifferentTimeUnit() {
    ExpiringPersonDifferentTimeUnit jWilkinson = ExpiringPersonDifferentTimeUnit.of("Jim Wilkinson", 7L);
    withTTLwTimeUnitAnnotationRepository.save(jWilkinson);

    Long expire = withTTLwTimeUnitAnnotationRepository.getExpiration(jWilkinson.getId());

    assertThat(expire).isEqualTo(7L*24*60*60);
  }
  ```
  
I will now recreate those in a standalone test to check the classloader issue you found. I assume the classloader provided by the test annotations/config is correct and the one on regular execution is not. I'll let you know. But if you see anything in these examples that jumps at you also report. Thanks!

**Comment by bsbodden** [comment]
@rasrov please test v0.8.2-SNAPSHOT that was published today (May 7) https://s01.oss.sonatype.org/content/repositories/snapshots/com/redis/om/redis-om-spring/0.8.2-SNAPSHOT/ let me know if that does it. Cheers.

**Comment by rasrov** [comment]
Perfect! I will test it on my service and let you know results.

Thanks for the effort! 🚀
