### ISSUE TITLE
Fail setting HuggingFaceTokenizer 

### ISSUE THREAD

**Issue by rasrov** [redis/redis-om-spring#246]
I'm trying to run my application, but I'm getting this message error:
`detailMessage -> Model "sentence-transformers/all-mpnet-base-v2" on the Hub doesn't have a tokenizer`

I have tried to find this tokenizer model into https://huggingface.co/models, but I don't found any model starting with **"sentence-transformers"**.

I have tried to start the application in debug mode and change the value of "identifier" (`HuggingFaceTokenizer.class:80`) to test with another model (`obrizum/all-mpnet-base-v2`) and it has returned a value, only if we are using version `0.22.1`.

**UPDATE**
https://github.com/huggingface/tokenizers/issues/1242

**Comment by rasrov** [comment]
The issue has been resolved by huggingface. 🚀

**Comment by bsbodden** [comment]
I did switch to the `v1` on the 0.8.2-SNAPSHOT but I will go back to v2 now that it is fixed.
