### ISSUE TITLE
Spring framework (plain)

### ISSUE THREAD

**Issue by Grogdunn** [redis/redis-om-spring#255]
Hi,
I cannot integrate with plain spring (not boot). I've tried but I expect the lib to generate some indexes, but it doesn't.

There are some examples, without spring boot?

Thanks,
Grogdunn

**Comment by bsbodden** [comment]
@Grogdunn I haven't had time to try that scenario. Can you create a sample project as a test bed, and I'll take a stab at figuring it out?
