### ISSUE TITLE
How to handle Redis restarts and an index not existing

### ISSUE THREAD

**Issue by rjdkolb** [redis/redis-om-spring#257]
I am still using the 0.6.4 version as I am stuck on Springboot 2 for now.

I have the following scenario:
1) Redis is started and the application starts creating the Redis index
2) Redis is restarted and all my data gets deleted
3) From an entityStream I try to count the number of rows stored

`var stream = entityStream.of(MyEntity.class);`

I then get the error:
_redis.clients.jedis.exceptions.JedisDataException: xxx.MyEntityIdx: no such index_

This of course makes sense since the index is created at startup.

I see there is a way to [check that an index](https://github.com/redis/redis-om-spring/blob/main/redis-om-spring/src/main/java/com/redis/om/spring/RediSearchIndexer.java#L202) exists and [create an index](https://github.com/redis/redis-om-spring/blob/main/redis-om-spring/src/main/java/com/redis/om/spring/RediSearchIndexer.java#L78), but I am not so sure I should be doing this.

Can you advice on the best way?

thanks

**Comment by sazzad16** [comment]
Best way? Using a [persistent](https://redis.io/docs/management/persistence/) server.

**Comment by bsbodden** [comment]
@rjdkolb Richard, do you have the option of making the Redis server persist the data like @sazzad16 suggested? 
If not, I think checking for the index and creating it on demand is ok, I don't a problem with that, but if you can have a persistent Redis server all the better,
