### ISSUE TITLE
question: InstantTypeAdapter timeInMillis , but it is EpochSecond, not  EpochMilli

### ISSUE THREAD

**Issue by guos** [redis/redis-om-spring#275]
for serialize/deserialize, any reason for only use EpochSecond, not EpochMilli?

master code as : 

 @Override
  public JsonElement serialize(Instant instant, Type typeOfSrc, JsonSerializationContext context) {
    long timeInMillis = instant.getEpochSecond();//   **<--- any reason for not use  instant.toEpochMilli() ?** 
    return new JsonPrimitive(timeInMillis);
  }

  @Override
  public Instant deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context)
      throws JsonParseException {
    return Instant.ofEpochSecond(json.getAsLong());
  }

**Comment by bsbodden** [comment]
I think I implemented that adapter as a Unix Timestamp, e.g. seconds since epoch. I'll change it to millis.

**Comment by bsbodden** [comment]
Now I remember, Date types are mapped to Unix Time, DateTime types are mapped to milliseconds. Instant should have been mapped as millis.
