### ISSUE TITLE
Dialect support (Syntax error when using stop words in Tags)

### ISSUE THREAD

**Issue by bastiaan-dev** [redis/redis-om-spring#283]
This question originates from failing test below. As I understand stopwords with spaces is handled differently depending on the selected DIALECT.

 It seems redis-om uses DIALECT 1 by default, which causes my test to fail with syntax error
```
@Test
  void testTagWithStopWords() {
    Person personA = new Person();
    personA.setName("PersonA");
    personA.setTagField("Person A");

    var resultA = entityStream.of(Person.class)
            .filter(Person$.TAG_FIELD.eq("Person A")) // 'a' is stop word, and tag is not escaped
            .collect(Collectors.toList()).stream().findFirst().get();
    assertThat(resultA.getName()).isEqualTo("PersonA");
  }
```

With using DIALECT 2 the test succeeds.
```
@Test
  void testTagWithStopWords() {
    Person personA = new Person();
    personA.setName("PersonA");
    personA.setTagField("Person A");

    var resultA = entityStream.of(Person.class)
            .dialect(2)
            .filter(Person$.TAG_FIELD.eq("Person A")) // 'a' is stop word, and tag is not escaped
            .collect(Collectors.toList()).stream().findFirst().get();
    assertThat(resultA.getName()).isEqualTo("PersonA");
  }
```

So by default (using DIALECT 1) there is an escaping bug. Is the goal for redis-om to support both DIALECTs? Or is the recommended approach to move to DIALECT 2? Is DIALECT 2 fully supported by redis-om?

**Comment by bsbodden** [comment]
I think the approach on dialect for the OM libraries is to keep whatever default Redis Stack has, when the default goes to 2, we will follow

**Comment by bastiaan-dev** [comment]
But when the default DIALECT 1 is followed, the first test case still stands and fails

```
@Test
  void testTagWithStopWords() {
    Person personA = new Person();
    personA.setName("PersonA");
    personA.setTagField("Person A");

    var resultA = entityStream.of(Person.class)
            .filter(Person$.TAG_FIELD.eq("Person A")) // 'a' is stop word, and tag is not escaped
            .collect(Collectors.toList()).stream().findFirst().get();
    assertThat(resultA.getName()).isEqualTo("PersonA");
  }
```

Currently we have to manually escape our tag fields, to make sure we don't run into syntax errors. Or switch our DIALECT to 2, which we rather don't do since its not the default.
