### ISSUE TITLE
Prefilter based on metadata for Vectors

### ISSUE THREAD

**Issue by ovidiu-petridean** [redis/redis-om-spring#287]
Hi,

First of all this is a great project! Congrats!

I have the following situation

@Data
@RequiredArgsConstructor(staticName = "of")
@NoArgsConstructor
@RedisHash
public class MyTextEmbedding {
    @Id
    private String id;

    @Indexed
    private String myDocId;

    @Indexed
    private String myDocTitle;

    Vectorize(destination = "sentenceEmbedding", embeddingType = EmbeddingType.SENTENCE)
    @NonNull
    private String segmentText;

    @Indexed(//
            schemaFieldType = SchemaFieldType.VECTOR, //
            algorithm = VectorAlgo.HNSW, //
            type = VectorType.FLOAT32, //
            dimension = 1536, // default openai
            distanceMetric = DistanceMetric.L2, //
            initialCapacity = 10
    )
    private byte[] sentenceEmbedding;
}

-----
and then

List<MyTextEmbedding> textEmbeddings = entityStream.of(MyTextEmbedding.class) //
                .filter(MyTextEmbedding$.SEGMENT_EMBEDDING.knn(6, embeddingAsByteArray)) //
                .sorted(MyTextEmbedding$._SEGMENT_EMBEDDING_SCORE) //
                .limit(6) //
                .collect(Collectors.toList());

Is there a way to "pre filter" so that I only search sentences in a particular doc with a specific id (myDocId) instead of searching in all docs?

Thanks!

**Comment by bsbodden** [comment]
Yes, indeed there is, you can tack on multiple `filter` calls before you call the KNN filter. There is an example of this type of `hybrid` search here https://github.com/redis/redis-om-spring/blob/main/redis-om-spring/src/test/java/com/redis/om/spring/search/stream/EntityStreamsHashVSSTests.java#L112
