### ISSUE TITLE
In filter not accepting list or array of string

### ISSUE THREAD

**Issue by sairamka** [redis/redis-om-spring#289]
The in filter method is allowing only individual comma separated string values. I can't convert my string list into individual comma Separated values. Is there any provision to pass array of strings?

**Comment by bsbodden** [comment]
Post an example of what you are trying to accomplish, include your models and repositories. Thanks!

**Comment by bsbodden** [comment]
You should be able to pass an array to something that takes varags...

```
public void doTheThing (String ... args) {
  // ...
}

doTheThing(new String[] { "s1", "s2"});  
```

**Comment by sairamka** [comment]
Thanks @bsbodden, this is worked 
  
 var c = (String[]) markets.toArray(new String[0]);
stream = stream.filter(TrendData$.MARKET.in(c));
