### ISSUE TITLE
Enable the ability to generate index creation for nested objects inside a List

### ISSUE THREAD

**Issue by pierrelambert** [redis/redis-om-spring#30]
```java
public class Parent {

      @Id
      private String id;

      @Indexed @NonNull
      private String name;
(....)

      @Indexed @NonNull
      private List<Child> childs;
}
````
And

```java
public class Child {

    @Id @NonNull
    private String id;
(...)
    @Indexed @NonNull
    private String name;

} 
```  
  
Expected capability : FT.CREATE "com.package.ParentIdx" "ON" "JSON" "PREFIX" "1" "com.package.Parent:" "SCHEMA" "$.name" "AS" "name" "TAG" (...) "$.childs[*].name" AS "childs_name" "TAG"

**Comment by bsbodden** [comment]
Apparently this is not yet supported on RediSearch/RedisJSON https://redis.io/docs/stack/json/indexing_json/#it-is-not-possible-to-index-json-objects - I'm closing and we'll revisit once the backend supports it.
