### ISSUE TITLE
Is there any equivalent support for redis-om-micronaut as we have for redis-om-spring

### ISSUE THREAD

**Issue by hhovhann** [redis/redis-om-spring#308]
Dear colleagues please share some information Is there any equivalent support for `redis-om-micronaut` as we have for `redis-om-spring` or planing to ave, otherwise could be redis-om-spring annotations also used in Micronaut entities and had the same ?

Regards

**Comment by bsbodden** [comment]
@hhovhann Not at the moment but I agree that Micronaut and Quarkus are important members of the Java microservices ecosystem.

**Comment by hhovhann** [comment]
Thanks @bsbodden for your quick response. What if I would try to use the existing annotations for the Micronaut application ? Will those works, because even if in very happy case will start something for Micronaut and Quarkus that will take long while.
Thanks

**Comment by bsbodden** [comment]
No, unfortunately the DI implementations in Spring, Quarkus and Micronaut are very different. But you should be able to use Jedis directly in the meantime.

**Comment by hhovhann** [comment]
Sure the low level we have :) At some point who will have for Quarkus (redis-om-quarkus) and Micronaut (redis-om-micronaut). Thanks for your answers
