### ISSUE TITLE
Prevent non-optimal indexing on List objects

### ISSUE THREAD

**Issue by pierrelambert** [redis/redis-om-spring#31]
In such configuration

```java
public class Parent {

      @Id
      private String id;

      @Indexed @NonNull
      private String name;
(....)

      @Indexed @NonNull
      private List<Child> childs;
}
````
AND

```java
public class Child {

    @Id @NonNull
    private String id;
(...) //Lots of Strings
    @Indexed @NonNull
    private String name;

    @NonNull 
    private Object infos;

}     
```

Actual behaviour: FT.CREATE "com.package.ParentIdx" "ON" "JSON" "PREFIX" "1" "com.package.Parent:" "SCHEMA" "$.name" "AS" "name" "TAG" (...) "$.childs[*]" AS "childs" "TAG"

while it should add the $.childs[*] path to the index , should it ignore it / return an error , but such an index is not functional.

**Comment by bsbodden** [comment]
@pierrelambert can you describe what you think the optimal index for the above example would be? For cases like that force the field to be serialized as a JSON array like this:

```java
  @NonNull
  @Indexed(separator = ",")
  @JsonAdapter(SetToStringAdapter.class)
  private Set<String> workType;
```

This works for things that can be flattened to a string element in the array. The `roms-permit` demo has an example:

https://github.com/redis/redis-om-spring/blob/main/demos/roms-permits/src/main/java/com/redis/om/permits/models/Permit.java#L53

For the non String collections, I could throw an exception on application startup? or I can fail it during annotation processing? Let me investigate the best way to handle it.

**Comment by pierrelambert** [comment]
Makes sense for List/Set of String.
When this is not a List/Set of String but a more complex object would not it make sense to directly index the @indexed fields of the nested object?

Exception warning it would be ignored maybe ?

**Comment by bsbodden** [comment]
The compromise, since Index creation happens on application startup, was to skip the field index creation and log an error like:

```
ERROR 87625 --- [           main] c.r.om.spring.RedisModulesConfiguration  : The collection "myList" of "InnerDoc"s in "OuterDoc" cannot be indexed. It is only possible to index a Collections of String or Boolean
2022-04-08 16:41:26.238  INFO 87625 --- [           main] c.r.om.spring.RedisModulesConfiguration  : Found 0 @RedisHash annotated Beans...
```
