### ISSUE TITLE
RedisTemplate name "redisTemplate" conflicts with other libraries

### ISSUE THREAD

**Issue by jawalker0** [redis/redis-om-spring#316]
Including the spring-boot-starter-webflux (in Spring Boot 3.1.1, possibly earlier) as a dependency in a project with Redis-OM 0.8.4 causes the following error on startup:

> Caused by: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'redisTemplate' defined in class path resource [com/redis/om/spring/RedisModulesConfiguration.class]: Cannot register bean definition [Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=true; factoryBeanName=com.redis.om.spring.RedisModulesConfiguration; factoryMethodName=redisTemplate; initMethodNames=null; destroyMethodNames=[(inferred)]; defined in class path resource [com/redis/om/spring/RedisModulesConfiguration.class]] for bean 'redisTemplate' since there is already [Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration; factoryMethodName=redisTemplate; initMethodNames=null; destroyMethodNames=[(inferred)]; defined in class path resource [org/springframework/boot/autoconfigure/data/redis/RedisAutoConfiguration.class]] bound.

If I add in the configuration property `spring.main.allow-bean-definition-overriding=true` then the problem goes away, but a global setting doesn't seem like the best fix for this.

**Comment by bsbodden** [comment]
I just added:

```xml
<dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-webflux</artifactId>
</dependency>
```

and bumped the SpringBoot version:

```xml
<version>3.1.1</version>
```

To the skeleton app here:

https://github.com/redis-developer/redis-om-spring-skeleton-app

and it starts properly. So I'm suspecting there has to be a combination of your dependencies that causes the issue.

**Comment by jawalker0** [comment]
@bsbodden  I've uploaded my sample here: https://github.com/jawalker0/redis-om-webflux

When I build, it runs tests looking for a local redis instance on 6379, so you can see the error when running tests, or if you try to start the app. If you comment out the webflux dependency, you'll see that the tests pass and the app can run.
