### ISSUE TITLE
Redis VSS with 'LIMIT 0 <K>'

### ISSUE THREAD

**Issue by qUser13** [redis/redis-om-spring#323]
I have a use case - need to find all records that have VSS score higher than specific threshold, there are no option to include this into filter (???) so decided to query for all results and then filter on Java side.

Based on docs, you can add `LIMIT 0 <K>` to query to get all results. See https://redis.io/docs/interact/search-and-query/search/vectors/#algorithm-specific-attributes. Is this supported?

**Comment by bsbodden** [comment]
Can you post your code?

**Comment by qUser13** [comment]
I used the code from VSS demo. I've tried something like (from `ProductController`):
```      
      List<Product> products = stream
          .filter(Product$.SENTENCE_EMBEDDING.knn(0, product.getSentenceEmbedding()))
          .sorted(Product$._SENTENCE_EMBEDDING_SCORE)
          .limit(K)
          .collect(Collectors.toList());
```
but it does not work. (not sure that even intended to work in this way)

**Comment by bsbodden** [comment]
> I used the code from VSS demo. I've tried (from `ProductController`):
> 
> ```
>       List<Product> products = stream
>           .filter(Product$.SENTENCE_EMBEDDING.knn(0, product.getSentenceEmbedding()))
>           .sorted(Product$._SENTENCE_EMBEDDING_SCORE)
>           .limit(K)
>           .collect(Collectors.toList());
> ```
> 
> but it does not work. (not sure that even intended to work in this way)

Sorry @qUser13 I don't quite get what the issue is, could you create a reproducer app that shows the problem. That'll be the easiest way for me to fix it. Cheers.
