### ISSUE TITLE
Support of Highlighting

### ISSUE THREAD

**Issue by ABHIJEET-MUNESHWAR** [redis/redis-om-spring#324]
Hi,

Does Redis OM Spring support [Highlighting](https://redis.io/docs/interact/search-and-query/advanced-concepts/highlight/) API?

I found more details about it in [RU203 Highlighting and Summarization](https://university.redis.com/courses/course-v1:redislabs+RU203+2023_07/courseware/d489ff692b5644b195f8582d63d0e312/bec41d42072a41fe8bcb4130873784f4/?child=first)

**Comment by HengCC** [comment]
I used version 0.8.7, and I encountered this error. Here is a portion of the code
`redis.clients.jedis.exceptions.JedisDataException: No such property `name``
```java
 .skip(pageable.getOffset())
                .limit(pageable.getPageSize())
                .highlight(SearchEntity$.NAME, Tuples.of("<strong>", "</strong>"))
                .collect(Collectors.toList());
```
I observed the final execution command, and it seems to be missing the return field. If this property is included in the return field, it doesn't throw an error. However, how do I specify this return field? Additionally, does Redis OM Spring have more detailed documentation? Currently, I can only refer to the source code.
@bsbodden

**Comment by bsbodden** [comment]
@HengCC yes please share your code, but be aware that there is a bug in RediSearch and highlighting is not currently supported on JSON, only Hashes, which might be what you are experiencing.

**Comment by HengCC** [comment]
Indeed, the index I'm using is in JSON format, Will JSON format be supported in the future? If not, I'm considering switching to hash mode, code demo below:
```java
    public Page<xxx> searchRaw(String keyword, Pageable pageable) {
        long total = entityStream.of(FileResourceSearchEntity.class)
                .filter(xxx$.CONTENT.containing(keyword).or(
                        xxx$.NAME.eq(keyword)
                                .or(xxx$.NAME.startsWith(keyword))
                                .or(xxx$.NAME.endsWith(keyword))
                                .or(xxx$.NAME.containing(keyword))
                ))
                .count();
        List<xxx> collect = entityStream.of(xxx.class)
                //.filter("(@name:" + keyword + ")|(@content:" + keyword + ")")
                .filter(xxx$.CONTENT.containing(keyword).or(
                        xxx$.NAME.eq(keyword)
                                .or(xxx$.NAME.startsWith(keyword))
                                .or(xxx$.NAME.endsWith(keyword))
                                .or(xxx$.NAME.containing(keyword))
                ))
                .skip(pageable.getOffset())
                .limit(pageable.getPageSize())
                .summarize(xxxx$.NAME)
                .highlight(xxxx$.NAME, Tuples.of("<strong>", "</strong>"))
                .collect(Collectors.toList());
        return new PageImpl<>(collect, pageable, total);
    }
```
