### ISSUE TITLE
Support of APPLY functions

### ISSUE THREAD

**Issue by ABHIJEET-MUNESHWAR** [redis/redis-om-spring#325]
Hi,

Does Redis OM Spring support [apply function](https://redis.io/docs/interact/search-and-query/search/aggregations/#list-of-datetime-apply-functions)?

**Comment by bsbodden** [comment]
Yes, see examples here https://github.com/redis/redis-om-spring/blob/main/redis-om-spring/src/test/java/com/redis/om/spring/search/stream/EntityStreamsAggregationsDocsTest.java#L335

**Comment by ABHIJEET-MUNESHWAR** [comment]
@bsbodden 
Yes there any Redis OM Spring example of using apply function without using `entityStream` & using `RedisDocumentRepository`

**Comment by bsbodden** [comment]
No, apply functions and aggregations are outside the scope of what Spring Data repositories are meant to do.
