### ISSUE TITLE
Indexing nested JSON object  impacts FT.SEARCH returning the records.

### ISSUE THREAD

**Issue by radhakrishna67** [redis/redis-om-spring#326]
I have issue with indexing nested object. When i index nested object, FT.SEARCH  is not returning the records.

Redis OM Spring version: 0.8.3
Spring Boot Version: 3.1.1
Java Version: openjdk version "17.0.2" 2022-01-18

here are Class details and indexing,

```
@Data
@ToString
@Document("User")
@RequiredArgsConstructor(staticName = "of")
@AllArgsConstructor(access = AccessLevel.PROTECTED)
public class User {

    @NotEmpty(message ="User email field value should not be null or empty")
    @Id
    private String userEmail;
    @Indexed private List<Role> roles;
    @Indexed private Set<String> projects;
    private List<Document> documents;
}

@Data
@RequiredArgsConstructor(staticName = "of")
public class Role {
    @Indexed private String projectId;
    @Indexed private List<String> roles;
    @Indexed private LocalDateTime joinTime;
	
}
```

```
"FT.SEARCH" "UserIdx" "@userEmail:{ra****\\@gmail\\.com}"
1) "0"
This is because of indexing  roles

"JSON.GET" "User:ra****@gmail.com"  works totally fine.
```

FT.SEARCH works totally fine when removing roles  Indexing.

**Comment by djptek** [comment]
JsonPath permits distinct notations for some equivalent paths, so:

`"$.projectRoles[0:].roles[*]"`

can also be written as 

`"$.projectRoles[0:].roles[0:]"`

Which delivers the same result and appears more consistent

**Comment by djptek** [comment]
see: [JSONPath syntax](https://redis.io/docs/data-types/json/path/#jsonpath-syntax)

**Comment by StanislavSerdiuk** [comment]
@bsbodden 
Did it resolve? I'm using version 2.0.10 and I'm facing the same problem. 
When I have a list of inner objects that I need to index, I see an alias like **ans[0:]imei** from the FT.INFO command. 
It prevents me from adding more than one item to the list, and when there are more, the whole document disappears from indext.
