### ISSUE TITLE
How do I search for percentages

### ISSUE THREAD

**Issue by rjdkolb** [redis/redis-om-spring#340]
using 0.8.7 I would like to search for percentages, but this does not seems to work as % is a wildcard.

The data I am trying in search for has discounts.

    @Test void testFindPercentages() {
      Company percentOff = repository.save(Company.of( //
              "Discount 50% off", 2011, //
              LocalDate.of(2021, 5, 1), //
              new Point(-122.066540, 37.377690), "stack@redis.com" //
      ));
      repository.save(percentOff);
    SearchStream<Company> stream = entityStream.of(Company.class);

    stream.filter("Disount 50% off").collect(Collectors.toList());// gives a Jedis syntax error
    List<Company> companies = stream.filter("50 \\%").collect(Collectors.toList());
    assertThat(companies).hasSize(1);//fails since it is 0 (not found)
    }

thanks

**Comment by bsbodden** [comment]
@rjdkolb Richard, the issue here is that with RediSearch `%` and other query special characters need to be escaped on insertion, the test below works:

```
@Test void testFindPercentages() {
    Company percentOff = companyRepository.save(Company.of( //
      "Discount 50\\% off", 2011, //
      LocalDate.of(2021, 5, 1), //
      new Point(-122.066540, 37.377690), "stack@redis.com" //
    ));
    companyRepository.save(percentOff);
    List<Company> companies = entityStream.of(Company.class).filter("Discount 50\\% off").collect(Collectors.toList());

    assertAll( //
      () -> assertThat(companies).hasSize(1),
      () -> assertThat(companies).extracting("name").contains("Discount 50\\% off")
    );
  }
  ```

**Comment by rjdkolb** [comment]
Thanks Brian. Makes sense.
