### ISSUE TITLE
about search query parameter binding,

### ISSUE THREAD

**Issue by HengCC** [redis/redis-om-spring#341]
When there is a duplicate parameter binding, it seems to be causing an issue. For example, in a query like this, 

```java
 @Query(value = "(@name:$keyword)|(@content:$keyword)")
 Page<xxxx> search(String keyword, Pageable pageable, SearchLanguage searchLanguage);
```
the generated SQL statement ends up looking something like this:
`"FT.SEARCH" "xxxxIdx" "(@name:sso)|(@content:$keyword)" "LANGUAGE" "chinese" "LIMIT" "10" "10"`

notice that the second parameter `$keyword` was not binding correctly

**Comment by justTimTim** [comment]
@bsbodden Hi! Is this bug no longer relevant?

**Comment by bsbodden** [comment]
> @bsbodden Hi! Is this bug no longer relevant? I prepared changes, but did not create a merge request

Oops, I thought your comment above meant is was part of a PR. Sorry re-opening

**Comment by justTimTim** [comment]
no problem) PR created
