### ISSUE TITLE
Pageable with sort column throws UnsupportedOperationException

### ISSUE THREAD

**Issue by tksarul** [redis/redis-om-spring#344]
I have a document entity and repository as below.

@Document(value = "npProduct")
public class NpProduct {

    @Id
    @Indexed
    @NonNull
    private String id;

    @Indexed
    @NonNull
    private String email;

    @Indexed
    @NonNull
    private String push;

    @Indexed
    @NonNull
    private String banner;
}

public interface NpProductRepository extends RedisDocumentRepository<NpProduct, String> {

}

**The below code works fine**
Pageable pageable = PageRequest.of(0, 10).withSort(Sort.unsorted());
Page<NpProduct> productPage = repository.findAll(pageable);

**The below code works throws UnsupportedOperationException**
Pageable pageable = PageRequest.of(0, 10).withSort(Sort.by(Sort.Direction.ASC, "email"));
Page<NpProduct> productPage = repository.findAll(pageable);

env details
JDK 17
'org.springframework.boot' version '3.1.2'
group: 'com.redis.om', name: 'redis-om-spring', version: '0.8.7'

**Comment by justTimTim** [comment]
Hi! Strange, but your design works for me without errors. Try it this way -> PageRequest.of(0, 10, Sort.by("email").ascending());
