### ISSUE TITLE
Can redis-om-spring generate a search query by a nested list item property

### ISSUE THREAD

**Issue by gediminasmorkys** [redis/redis-om-spring#349]
Is it possible to search for a Redis @Document, or Redis @Hash by a single property in a nested list?

E.g.: 

- a Developer entity can have a List<Library> contributions
- a Library entity can have a String title field, e.g. "redis-om-spring"
- From a cached list of Developer entities, I want to search for only the Developer that has contributed to a Library titled "redis-om-spring"

Does redis-om-spring support such a query?

**Comment by bsbodden** [comment]
Yes, take a look at this tests for some examples https://github.com/redis/redis-om-spring/blob/main/redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/ComplexDocumentSearchTest.java#L312

**Comment by gediminasmorkys** [comment]
> Yes, take a look at this tests for some examples https://github.com/redis/redis-om-spring/blob/main/redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/ComplexDocumentSearchTest.java#L312

Thanks a lot for the response.

I'd like to clarify. 

I wondered if I could filter by the properties of the nested list, like this:
https://github.com/redis/redis-om-spring/pull/352/files

**Comment by abilash-sethu** [comment]
> > Yes, take a look at this tests for some examples https://github.com/redis/redis-om-spring/blob/main/redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/ComplexDocumentSearchTest.java#L312
> 
> Thanks a lot for the response.
> 
> I'd like to clarify.
> 
> I wondered if I could filter by the properties of the nested list, like this: https://github.com/redis/redis-om-spring/pull/352/files

Hi @gediminasmorkys , Did you find a solution for the above?

**Comment by gediminasmorkys** [comment]
> > > Yes, take a look at this tests for some examples https://github.com/redis/redis-om-spring/blob/main/redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/ComplexDocumentSearchTest.java#L312
> > 
> > 
> > Thanks a lot for the response.
> > I'd like to clarify.
> > I wondered if I could filter by the properties of the nested list, like this: https://github.com/redis/redis-om-spring/pull/352/files
> 
> Hi @gediminasmorkys , Did you find a solution for the above?

No, we switched back to doing our complex filtering in application code, and using Hazelcast to sync the raw data between our application instances.
