### ISSUE TITLE
connect to cluster always go to localhost 

### ISSUE THREAD

**Issue by guos** [redis/redis-om-spring#350]
when i use redis-om connect to one node of redis with redisjson all works fine, 
but i am consider connect to a cluster  it looks not have issue on connection, but when do query , it always go to localhost, is OM support cluster ? or myusage wrong    

	@Bean
	public JedisConnectionFactory jedisConnectionFactory() {
		final JedisPoolConfig poolConfig = new JedisPoolConfig();
		poolConfig.setMaxTotal(env.getJedis().getPool().getMaxActive());
	       poolConfig.setMinIdle(env.getJedis().getPool().getMinIdle());
	       poolConfig.setMaxIdle(env.getJedis().getPool().getMaxIdle());
               log.info("Jedis pool info: {}",JSON.toJSONString(poolConfig));
		final int timeout = 10000;
		final JedisClientConfiguration jedisClientConfiguration = JedisClientConfiguration.builder()
				.connectTimeout(Duration.ofMillis(timeout))
				.readTimeout(Duration.ofMillis(timeout))
				.usePooling()
				.poolConfig(poolConfig).build();

		if(clusterModel) {
			return new JedisConnectionFactory(clusterConfig(), jedisClientConfiguration);
		}

		return new JedisConnectionFactory(standaloneConfiguration(), jedisClientConfiguration);
	}

**Comment by bsbodden** [comment]
@guos unfortunately, that feature is not ready yet https://github.com/redis/redis-om-spring/issues/48

**Comment by guos** [comment]
Many thanks and looking forward

**Comment by guos** [comment]
@bsbodden  if not cluster, how about sentinel ? is that fine
