### ISSUE TITLE
TTL within @Document is not updated while saving entity

### ISSUE THREAD

**Issue by ShivaShanmugam3792** [redis/redis-om-spring#356]
I have been trying to use TTL with RedisDocumentRepository. I have used TTL in my entity which is document
    @NonNull
    @TimeToLive(unit = TimeUnit.SECONDS) Long ttl;

I can see that the document is saved with TTL only when I use saveAll(entities) and not saved with TTL when I use save(entity)

I see that implementation for saveAll under SimpleRedisDocumentRepository, executes expire with pipeline if ttl is present

**Comment by bsbodden** [comment]
Thanks for reporting!

**Comment by bsbodden** [comment]
@ShivaShanmugam3792 can you check your current usage against the tests here https://github.com/redis/redis-om-spring/blob/main/redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/DocumentTTLTests.java

I just tested `.save` on Document Repo locally and it seems to be working, maybe your repository definition is not correct? Can you post your code?
