### ISSUE TITLE
Exception during index creation leads to missing schema in entityClassToSchema map which causes Query by Example to fail

### ISSUE THREAD

**Issue by patbrdt** [redis/redis-om-spring#367]
Hello

Assuming having a simple document like this

```
@RequiredArgsConstructor(staticName = "of")
@NoArgsConstructor
@Data
@Document
public class Product {

    @Id
    @Indexed
    @NonNull
    private String sku;

    @Searchable
    @NonNull
    private String title;
}
```

When the application first starts the index will be created properly but on the next run you will see a warning message in the console.

**WARN 27424 --- [           main] com.redis.om.spring.RediSearchIndexer    : Skipping index creation for com.example.ProductIdx because Index already exists**

One would assume this is not an issue but it is when you want to run a **Query by Example**

```
Product template = new Product();
template.setTitle("abc");
Example<Product> example = Example.of(template, ExampleMatcher.matchingAll());
return repo.findAll(example);
```

In this example redis should search in the **title** field but instead follwing command gets executed

```
com.example.ProductIdx" "*" "LIMIT" "0" "10000" "DIALECT" "1"
```

This is because the call to `entityClassToSchema.put(cl, schema);` in **com.redis.om.spring.RediSearchIndexer#createIndexFor** gets ommited because of the exception during index creation.

In **com.redis.om.spring.search.stream.ExampleToNodeConverter#processExample** the schema will be queried from the indexer. Since it does not get added because of the exception nothing gets processed.

Ist this a bug or am i doing something wrong here?

I am using version 0.8.7 of this library

Thank you for helpful input!

**Comment by patbrdt** [comment]
One workaround is this #366 but still seems a bug to me. I dont't want to drop the index any time my application starts up

**Comment by bsbodden** [comment]
This is a bigger issue that's being discussed here https://github.com/redis/redis-om-spring/issues/26
