### ISSUE TITLE
@Aggregation Example

### ISSUE THREAD

**Issue by dsinghal-nice** [redis/redis-om-spring#375]
I am trying to use RediSearch module for my JSON objects, and want to perform aggregation query, but haven't found any live examples for this, I have done the below steps, but still couldn't follow on how to use `@Aggregation`

1. @EnableRedisDocumentRepositories on my SpringBootApplication
2. Created my model with `@Document` annotation
3. Created my repository and extended with RedisDocumentRepository
4. Created UnifiedJedis bean and autowired in my service, and used .ftAggregate command to execute the groupBy.

Can you help me here to provide examples for below use cases:

1. Filter data based on some criteria
2. Group by multiple fields 
3. Sort by multiple fields.
 
Also, can you please let me know when the support for redis.clients:jedis:5.0.0 will be provided by ROMS.

Apologies if this is not the right forum!

**Comment by bsbodden** [comment]
Aggregation support is the most complete under the EntityStreams API, see examples:

- https://github.com/redis/redis-om-spring/blob/main/redis-om-spring/src/test/java/com/redis/om/spring/search/stream/EntityStreamsAggregationsDocsTest.java
- https://github.com/redis/redis-om-spring/blob/main/redis-om-spring/src/test/java/com/redis/om/spring/search/stream/EntityStreamsAggregationsDocsPagingTest.java
- https://github.com/redis/redis-om-spring/blob/main/redis-om-spring/src/test/java/com/redis/om/spring/search/stream/EntityStreamsZipCodeDataAggregationsTest.java

Let me know if that helps...

**Comment by dsinghal-nice** [comment]
@bsbodden Thanks!! I got the understanding on how to use aggregation with entity streams. Just one more question, do we also have @Aggregation annotation available and if yes then can you share few examples of it.

**Comment by bsbodden** [comment]
> @bsbodden Thanks!! I got the understanding on how to use aggregation with entity streams. Just one more question, do we also have @Aggregation annotation available and if yes then can you share few examples of it.

See:
- https://github.com/redis/redis-om-spring/blob/main/redis-om-spring/src/test/java/com/redis/om/spring/annotations/hash/fixtures/GameRepository.java

and 

- https://github.com/redis/redis-om-spring/blob/main/redis-om-spring/src/test/java/com/redis/om/spring/annotations/hash/AggregationAnnotationTest.java
