### ISSUE TITLE
Support standard interface/class based projections

### ISSUE THREAD

**Issue by abilash-sethu** [redis/redis-om-spring#380]
**Question**: Does Redis om Spring support standard interface/class-based projections?

For example: 

Here is my projection class:

`public interface CachedClassificationSkimmedProjection {
  Integer getSurId();
  String getName();
  String getIconUrl();
}`

My document repository:

`@Repository
public interface ClassificationDocumentRepository extends
    RedisDocumentRepository<ClassificationDoc, Integer> {

  List<CachedClassificationSkimmedProjection> findByEnterpriseId(Integer id);

  List<ClassificationDoc> findAllByEnterpriseId(Integer id);
  
}`

It always returns empty results, I saw the spring data Redis itself supports projections (https://docs.spring.io/spring-data/redis/reference/repositories/projections.html). 

@bsbodden Can you please advise?

**Comment by bsbodden** [comment]
There is no support for repository projections for now, but you can use `EntityStream` API to get individual field search results. See usage of the `.map` method here https://github.com/redis/redis-om-spring/blob/main/redis-om-spring/src/test/java/com/redis/om/spring/search/stream/EntityStreamDocsTest.java#L386

**Comment by abilash-sethu** [comment]
@bsbodden This really helps, Thank you.

**Comment by bsbodden** [comment]
Implemented in 0.9.1
