### ISSUE TITLE
Modifying roms-vss Demo for RedisJSON Document Storage

### ISSUE THREAD

**Issue by shannonantony** [redis/redis-om-spring#382]
@bsbodden,

Firstly, I want to express my gratitude for all the fantastic work you've been doing!

I have a question regarding the roms-vss sample. Currently, my model objects are in the @Document format rather than #RedisHash, and I'm using the RedisDocumentRepository to store my data. I was wondering if it's possible to modify the roms-vss sample to work with my data stored in JSON instead of Hash.

If this is achievable, could you guide me on how to make these modifications?

Thank you once again for your time and assistance.

Best regards,
Jay

**Comment by shannonantony** [comment]
Thanks @bsbodden 

btw, I noticed https://github.com/redis/redis-om-spring/blob/main/redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/ProductRepository.java is using RedisEnhancedRepository. Was it supposed to use RedisDocumentRepository?

I tried both, but records are not getting loaded into redis. No errors though

thanks

Jay

**Comment by bsbodden** [comment]
That was an oversight, copy-pasta malady, but I've fixed it now. Thanks for pointing it out. I did ran the tests with the change and they continue to work since the two repo types are nearly identical now. 

But please post a reproducer of your issue and I'll work to fix it.

**Comment by shannonantony** [comment]
Great. it worked. minor bug on my side. 

thanks again for your support !

Happy coding !!!

**Comment by shannonantony** [comment]
@bsbodden  I am trying to understand how do I create 
com.redis.om.vss.domain.Product$ in the roms-vss demo sample

I am getting following error during compilation.

java.lang.Error: Unresolved compilation problems: 
	Product$ cannot be resolved
	Product$ cannot be resolved

thanks again

Jay

**Comment by bsbodden** [comment]
@shannonantony See https://github.com/redis/redis-om-spring#explicitly-configuring-om-as-an-annotation-processor

This typically just works but sometimes in needs a little nudging. Also keep an eye on the build output in case there is an issue that prevents the generation of the metamodel

**Comment by shannonantony** [comment]
@bsbodden  It was working yesterday, but now it does not work

I see compilation issue : Product$ not found. Any steps to regenerate Product$ classes?

appreciate your help. 
thanks

Jay

 List<Pair<Product,Double>> productsAndScores = stream
          .filter(Product$.SENTENCE_EMBEDDING.knn(K, product.getSentenceEmbedding())) //
          .sorted(Product$._SENTENCE_EMBEDDING_SCORE) //
          .limit(K) //
          .map(Fields.of(Product$._THIS, Product$._SENTENCE_EMBEDDING_SCORE)) //
          .collect(Collectors.toList());

**Comment by shannonantony** [comment]
Btw, I am using jdk 21 with springboot 3.2.x. Will that be the issue? thansk @bsbodden
