### ISSUE TITLE
Does redis-om-spring has ability of setting index name explicitly?

### ISSUE THREAD

**Issue by prussian94** [redis/redis-om-spring#384]
Can you set repository index name in redis-om-spring?

I have 2 microservices one is for writing and the other one is for reading data.

I am writing data to redis at one of my microservices. Let's say it writes data to index 

`com.project.models.RedisMessage`

And I'm trying to read those messages at another microservice. But since the package names are different (because they're 2 different repositories at different projects.) Index names are not matching. Like the second microservice index name set as

`com.anotherProject.models.RedisMessage`
by the redis-om-spring.

Is there a way to set index name explicitly for Document ?

**Comment by justTimTim** [comment]
As far as I remember this should work -> @Document("myDoc")

**Comment by prussian94** [comment]
Yes it solves my problem. Thanks a lot Tim!

**Comment by xMilos** [comment]
Why is on FT._LIST still full index name ? Also need to use full index name on ft.search "com.example.RedisIndex" is there a different property as well to set for this @justTimTim do you happen to know ?

**Comment by justTimTim** [comment]
> Why is on FT._LIST still full index name ? Also need to use full index name on ft.search "com.example.RedisIndex" is there a different property as well to set for this @justTimTim do you happen to know ?

sounds like a bug. I understand correctly that you specified the alias through “@document("alias")”, but the search for this alias does not work? Can you provide a code example to make it clearer?

**Comment by xMilos** [comment]
@prussian94 yes

**Comment by justTimTim** [comment]
@xMilos @prussian94 just being discussed https://github.com/redis/redis-om-spring/issues/385

**Comment by xMilos** [comment]
So, in conclusion this will be supported with new option **indexAlias** on @Document or the existing **alias** will be for index instead of document prefix ?
