### ISSUE TITLE
repo.findAll(sort) throws UncategorizedKeyValueException

### ISSUE THREAD

**Issue by Rohan-RPJ** [redis/redis-om-spring#388]
Hi @bsbodden ,

As title says, running repository.findAll(Sort.by(Direction.DESC, "id")); method throws UncategorizedKeyValueException. 

Can't figure out why. The id field is sortable.

**Comment by bsbodden** [comment]
@Rohan-RPJ please post the model (or a sanitize version of it), the repo interface and some sample data (a few records should do). Thanks

**Comment by Rohan-RPJ** [comment]
@bsbodden , we took latest version 0.8.8 and it worked! Thankyou for your support
