### ISSUE TITLE
Eq method should not escape characters

### ISSUE THREAD

**Issue by fabrizio-cannizzaro** [redis/redis-om-spring#389]
The eq method is escaping special characters, with the result in that case return ever false

**Comment by bsbodden** [comment]
@fabrizio-cannizzaro can you post a small reproducer? Thanks

**Comment by fabrizio-cannizzaro** [comment]
Here a snippet:

SearchStream<MeetingDetailDocument> searchStream = entityStream.of(MeetingDetailDocument.class)
if (organizingEntity != null) {
    stream.filter(MeetingDetailDocument$.ORGANIZING_ENTITY.eq(organizingEntity)); 
}
organizing entity is a String.
if we pass"S&D" to eq method, it will be escaped to "S\&D" and return false, because in Redis the value is not escaped.

**Comment by justTimTim** [comment]
I believe this may have something to do with the tokenization rules in RediSearch https://redis.io/docs/interact/search-and-query/advanced-concepts/escaping/

**Comment by fabrizio-cannizzaro** [comment]
You are right, the problem was caused by the index: if they already and are added new fields the index is not recreated at startup
