### ISSUE TITLE
The eq method is not escaping the / character

### ISSUE THREAD

**Issue by fabrizio-cannizzaro** [redis/redis-om-spring#391]
Here a snippet:

SearchStream searchStream = entityStream.of(MeetingDetailDocument.class)
if (organizingEntity != null) {
stream.filter(MeetingDetailDocument$.ORGANIZING_ENTITY.eq(organizingEntity));
}
organizing entity is a String (TAG).
if we pass"a/b" to eq method, the / is not escaped and return false, because in Redis we have "a/b" value.

**Comment by bsbodden** [comment]
@fabrizio-cannizzaro could you test on your end?

**Comment by fabrizio-cannizzaro** [comment]
Thank you @bsbodden. In which version will you release the fix?

**Comment by bsbodden** [comment]
@fabrizio-cannizzaro sorry I'll be out on `v.0.9.0-SNAPSHOT` waiting to add a few more things before I push it out
