### ISSUE TITLE
Adding a ttl (expiry) for an entity that is saved in the repository

### ISSUE THREAD

**Issue by dxps** [redis/redis-om-spring#398]
Hi everyone!

Currenlty, there is no option to set the TTL (Expiry) for an entity that is saved using `RedisDocumentRepository<MyEntity, MyId>`.

Interesting enough, that repository exposes a `getExpiration(id)`, but not a `setExpiration(ttl)` altough this one should be set either at the `.save(entity)` time or at the entity definition level (through a Redis OM annotation).

This has been previously added to Node.js version of Spring OM, see [here](https://github.com/redis/redis-om-node/issues/35).

Are there any plans to add it?

Thanks!

**Comment by bsbodden** [comment]
The TTL feature has been there from almost the beginning, just missing docs...  THere are several ways to control the TTL, they all work via the `timeToLive` argument on the `@Document` annotation like:

```java
@Document(timeToLive = 5)
public class ExpiringPersonWithDefault {
  @Id String id;
  @NonNull
  String name;
}
```

with a default TTL for all object on save, or with a explicit TTL that overrides the default like:

```java
@Document(timeToLive = 5)
public class ExpiringPerson {
  @Id String id;
  @NonNull @Indexed
  String name;
  
  @NonNull
  @TimeToLive Long ttl;
}
```

which can be used as:

```java
ExpiringPerson mWoodger = ExpiringPerson.of("Mike Woodger", 15L);
```
and to check the TTL the `RedisDocumentRepository` interface has a method:

```java
Long getExpiration(ID id);
```

Let me know if that satisfies your use case. Cheers.

**Comment by dxps** [comment]
Got it. Thanks so much for the quick feedback! :pray:  Cheers!
