### ISSUE TITLE
Trouble with performing geospatial queries

### ISSUE THREAD

**Issue by prussian94** [redis/redis-om-spring#402]
Greetings, I'm implementing my code exactly as documentation says but geospatial queries always return 0.

- I have a location field inside my model (its type is org.springframework.data.geo.Point)
- I insert some objects to redis
- I try to make a geospatial query with: 
`     List<RedisMessage> findByLocationNear(Point point, Distance distance);
`
but even if I give 50000 kilometers at any point, it always returns 0. am I missing something here? Any helps are appreciated.

**Comment by bsbodden** [comment]
@prussian94 can you share some sample data so that I can write a test to replicate the issue?
