### ISSUE TITLE
Java 21 Support

### ISSUE THREAD

**Issue by kramer** [redis/redis-om-spring#405]
Is there a plan to support Java 21 soon?
Currently the builds fail with:

> [WARNING] Supported source version 'RELEASE_17' from annotation processor 'com.redis.om.spring.metamodel.MetamodelGenerator' less than -source '21'

**Comment by bsbodden** [comment]
Yes, it's on the roadmap! ETA in the next month

**Comment by sujay-patni-ofb** [comment]
Is the Java 21 support still in the pipeline?

**Comment by bsbodden** [comment]
Yes, 1.0.0 release will be Java 21

**Comment by sumitjainn** [comment]
@bsbodden Please let me know if you need any help with this

**Comment by bsbodden** [comment]
Thanks @sumitjainn - I had a branch ready but it needed more testing. It is merged now. https://github.com/bsbodden/redis-om-spring/commit/2e797b6e0c9ed3f06a820c5d2f190bea186b7d1f

If should support 17 and 21, perhaps 11 too but I haven't tested that
