### ISSUE TITLE
Setting TTL on @Document object

### ISSUE THREAD

**Issue by shannonantony** [redis/redis-om-spring#410]
@bsbodden, Thanks again for the great work.

I tried to set the TTL for Document object as below

@Document(timeToLive = 86400)
public class Device implements Serializable{
   @TimeToLive Long ttl;

However, I have no luck to make it work so far. Can you pleae suggest a method to set the expiry for JSON objects using redis-om

thanks

Jay

**Comment by bsbodden** [comment]
Jay, I'll investigate and report back.

**Comment by bsbodden** [comment]
@shannonantony see if you can do a small app with the classes above and see if that works. If it doesn't please create a reproducer app and I can start working on a resolution. Cheers!

**Comment by justTimTim** [comment]
@shannonantony my colleagues encountered a similar problem, it turned out that they did not have the “redisearch” module installed. Perhaps you have something similar

**Comment by shannonantony** [comment]
No, I have the redis-stack installed. but I see TTL set to -1

**Comment by justTimTim** [comment]
@shannonantony Try removing the index manually using "FT.DROPINDEX __idx_name__" and restart your application

**Comment by shannonantony** [comment]
It is working now. thanks for your help.
