### ISSUE TITLE
Enable customization of the Redis Indices when declaring an Entity

### ISSUE THREAD

**Issue by bsbodden** [redis/redis-om-spring#415]
Add a property to the `Document` annotation as:
```java
@Document(indexName = "myCustomIndexName")
public class MyEntity {
}
```

Problem, we will have to replace `RedisHash` with a Redis OM specific annotation. Or add an extra annotation just for the `indexName`

**Comment by dxps** [comment]
Awesome! 
@bsbodden Do you have an ETA for the 0.9.1 release that includes this fix, please?
Thanks!
