### ISSUE TITLE
com.redis.om.spring.ops.json.JSONOperationsImpl is using JSONArray.isEmpty() method which does not exist

### ISSUE THREAD

**Issue by shannonantony** [redis/redis-om-spring#417]
Hi @bsbodden , I am getting Runtime exception since 

com.redis.om.spring.ops.json.JSONOperationsImpl is using JSONArray.isEmpty() method which does not exist

please let me know if I am missing anything.

thanks

Jay

**Comment by bsbodden** [comment]
It's likely a dependency you are pulling that's bringing an old version of the JSON jar
<img width="621" alt="Screenshot 2024-04-21 at 11 33 38 AM" src="https://github.com/redis/redis-om-spring/assets/24109/b0b8365d-3ef2-4332-8ef0-37ba375ebe92">

It should be this version:

<img width="297" alt="Screenshot 2024-04-21 at 11 40 24 AM" src="https://github.com/redis/redis-om-spring/assets/24109/42386c69-b2f9-4c3c-a861-63ecfd443eca">
