### ISSUE TITLE
The SearchOperations<String>.search() interface does not set the returnFields attribute; why does the result set not include any field data?

### ISSUE THREAD

**Issue by mayipepsi** [redis/redis-om-spring#428]
<img width="697" alt="image" src="https://github.com/redis/redis-om-spring/assets/42597929/4ce2d688-6440-431e-99f7-0dcda437cfea">

**Comment by mayipepsi** [comment]
Client command: FT.SEARCH idx "*"

**Comment by bsbodden** [comment]
@mayipepsi the `Query` class is from the Jedis library, this ticket belongs there. But from visual inspection my guess is you are missing the `"$"` on the fields for the JSON object. Remember Jedis is a lower-level of abstraction library which works as close to the raw commands as possible. https://github.com/redis/jedis/blob/7aad706e61f8686e5801179689dc6f790ccbb196/src/test/java/redis/clients/jedis/modules/search/JsonSearchTest.java#L193
