### ISSUE TITLE
Migrate to Jedis 4.2

### ISSUE THREAD

**Issue by gkorland** [redis/redis-om-spring#43]
```
    <jredisjson.version>1.5.0</jredisjson.version>
    <jredisearch.version>2.2.0</jredisearch.version>
    <jredisbloom.version>2.2.0</jredisbloom.version>
```
Should be replace with Jedis 4.2

**Comment by bsbodden** [comment]
@gkorland I really would like to do that but I'm getting the Jedis dependency from Spring Data Redis, at the moment, on the current release they are at `3.7.0` and I believe just overriding that with `4.2` would break SDR which we rely on for some of the lower-level APIs. Let's discuss soon!

**Comment by gkorland** [comment]
https://github.com/spring-projects/spring-data-redis/pull/2287

**Comment by oalles** [comment]
https://github.com/spring-projects/spring-data-redis/pull/2287 
Already closed :clap:

**Comment by bsbodden** [comment]
> spring-projects/spring-data-redis#2287

I got a branch ready, waiting for a few dependencies to be published and we should be good to go.

**Comment by PaulBenn-UnlikelyAI** [comment]
Hi there - is there a release version coming out soon with this change? The last update was in May, so just checking in now that someone is assigned to it. Cheers

**Comment by bsbodden** [comment]
> Hi there - is there a release version coming out soon with this change? The last update was in May, so just checking in now that someone is assigned to it. Cheers

`0.6.0` was just released, but the Jedis upgrade is still in the works. So likely close to `1.0.0`

**Comment by bsbodden** [comment]
Done!
