### ISSUE TITLE
Skip index creation and use existing index

### ISSUE THREAD

**Issue by dasivon021** [redis/redis-om-spring#437]
Hi, is there a way to make redis-om-spring skip index creation and tell it to use existing index in Redis cluster?

Context:
We have a Redis cluster on the cloud. Cluster is configured to be read-only for my application only, other preexisting application(s) had already created the full-text index and can do reads/writes. My app will be executing search queries exclusively, for example:

`"FT.SEARCH" "com.example.demo.entity.StudentIdx" "@User\\-Name:{pera} @Event\\-Timestamp:[1611995400000 1715774820418]" "SORTBY" "eventTimestamp" "ASC" "LIMIT" "0" "100000"` (this fails because no index exist with that name)

Now, on the startup in my application, I get to see a log:

`2024-05-15T15:14:36.730+02:00  WARN 36624 --- [demo] [  restartedMain] com.redis.om.spring.RediSearchIndexer    : Skipping index creation for com.example.demo.entity.StudentIdx because READONLY You can't write against a read only replica.`

Exception is caught on this [line](https://github.com/redis/redis-om-spring/blob/0679d17d651f3ee89f66656025f5b4d5bffff4e5/redis-om-spring/src/main/java/com/redis/om/spring/RediSearchIndexer.java#L132) as `redis.clients.jedis.exceptions.JedisDataException: READONLY You can't write against a read only replica.`

Would it be possible to modify the library so that it uses existing index?

Hash records are stored in this format:

```
my:key:space:abc

  "First-Name": "UWucCgR+GAiakfbSpzuLBQ==",
  "Event-Timestamp": "182952385124",
  "User-Name": "marc.mk"
```

Index is created with this command:

`FT.CREATE org:company:index:student-idx ON HASH PREFIX 1 my:key:space SCHEMA User-Name TAG SORTABLE First-Name TAG SORTABLE Event-Timestamp NUMERIC SORTABLE`

So something like this, as an example of course:

```
@Data
@Builder
@RequiredArgsConstructor(staticName = "of")
@AllArgsConstructor(access = AccessLevel.PROTECTED)
@RedisHash(indexCreation=false, indexName="org:company:index:student-idx")
public class Student {

    @Id
    private Stringid;

    @Indexed(alias = "User-Name")
    private String userName;

    @Indexed
    private LocalDateTime eventTimestamp;

}
```

**Comment by dasivon021** [comment]
@bsbodden Hi Brian, thanks for **0.9.1** version and for quick fix in [433](https://github.com/redis/redis-om-spring/issues/433)! Helped a lot! Now, we face another issue.

**Comment by bsbodden** [comment]
@sazzad16 any suggestions on how best to approach this?

**Comment by sazzad16** [comment]
I don't understand. I see the `indexCreation=false` option.
@bsbodden Don't you consider that option? Shouldn't honoring it be enough?

**Comment by dasivon021** [comment]
@sazzad16 Hi, those two properties in the annotation are not there. I just give this as possible implementation example. If they were available I would use the of course :) Sorry for the confusion, wanted to explain better

**Comment by sazzad16** [comment]
Well, in that case:
@bsbodden something like `indexCreation=false` is my suggestion.

**Comment by dasivon021** [comment]
Yes correct, it's just a warning, my suggestion was that lib shouldn't even try to create an index in case `indexName="org:company:index:student-idx"` is specified (and pre-created on cluster). So I just need a way how to tell the lib to use pre-created index on the cluster. When I issue search queries, the lib should use that specified index instead of default which is class package + class name + "Idx".

**Comment by bsbodden** [comment]
@dasivon021 you can now do this https://github.com/redis/redis-om-spring/blob/main/redis-om-spring/src/test/java/com/redis/om/spring/fixtures/document/model/ModelSkipIfExist.java

New annotation was required because we can't change `RedisHash` as it is not owned by this project.

**Comment by dasivon021** [comment]
Hi @bsbodden Thank you very much for 437, 438 & 439. Would like to test them asap, for which version I should look for and when will be available?

**Comment by dasivon021** [comment]
Hi @bsbodden, I don't know if I explained well but beside skipping index creation, I should also be able to mark which index name I want instead to be used in all queries. So your new annotation, should be used as:
`
@IndexingOptions(creationMode = IndexCreationMode.SKIP_ALWAYS, indexName="someOtherIndexNameWhichDevOpsCreated")`

As of now, search queries are still using package name with suffix Idx, and name that needs to be used is `someOtherIndexNameWhichDevOpsCreated`

**Comment by bsbodden** [comment]
You can do that with `@Document` entities like : `@Document(indexName = "MyCustomIndex")` unfortunately we can't change `@RedisHash` the same way. So I'll consider adding it to `IndexingOptions` to handle that.

**Comment by dasivon021** [comment]
So I just added `@Document` to my entity, but in my understanding `@Document` should be used when storing JSON in redis, or it can be used with hashes as well? 

This is the entity:

```
@Data
@Builder
@RequiredArgsConstructor(staticName = "of")
@AllArgsConstructor(access = AccessLevel.PROTECTED)
@IndexingOptions(creationMode = IndexCreationMode.SKIP_ALWAYS)
@Document(indexName = "myCustomIndex") //got it via "FT._LIST" command
@RedisHash
public class Student{ ... }
```

Getting:` org.springframework.dao.InvalidDataAccessApiUsageException Caused by: redis.clients.jedis.exceptions.JedisDataException: path.to.class.StudentIdx: no such index`

**Comment by bsbodden** [comment]
You are right, you can't use `@Document` and `@RedisHash` together.

**Comment by dasivon021** [comment]
Do you need reproducible example perhaps?

**Comment by bsbodden** [comment]
No, no need, what I'm saying is that custom index name support was only there for Document mapped entities, we'll add it for Hashes via the IndexingOptions

**Comment by bsbodden** [comment]
@dasivon021 it's there now, just use `indexName` with `IndexingOptions` - you might need to delete the JAR from your Maven .m2/repository to get the fresh snapshot

**Comment by dasivon021** [comment]
Unfortunately, I'm getting same exception :( The `indexName` is still not used with search query. Please, try this [example](https://github.com/dasivon021/demo-redis/tree/indexing_options) (readme), I did delete JAR from local maven repo.

**Comment by bsbodden** [comment]
@dasivon021 try again, new snapshot has been published

**Comment by dasivon021** [comment]
Hi, thanks for your effort! Now, exception is no longer appearing and `indexName` from the annotation is used in search query. However, with `creationMode = IndexCreationMode.SKIP_IF_EXIST, indexName = "myIndexStudent"` on every app restart, library issues a full `FT.CREATE` command with index name set in `indexName` which is misleading and shouldn't attempt to create index.

If I set `creationMode = IndexCreationMode.SKIP_ALWAYS, indexName = "myIndexStudent"`, then it's ok.
