### ISSUE TITLE
SORTBY clause property not escaped in finder queries

### ISSUE THREAD

**Issue by dasivon021** [redis/redis-om-spring#438]
I have a model like this:

```
@Data
@Builder
@RequiredArgsConstructor(staticName = "of")
@AllArgsConstructor(access = AccessLevel.PROTECTED)
@RedisHash
public class Student {

    @Id
    private Long id;

    @Indexed(alias = "User-Name")
    private String userName;

    @Indexed(alias = "Event-Timestamp")
    private LocalDateTime eventTimestamp;

}
```

Repository:
```
@Repository
@Transactional(readOnly = true)
public interface StudentRepository extends RedisEnhancedRepository<Student, Long>, QueryByExampleExecutor<Student> {

    List<Student> findByUserNameAndEventTimestampBetweenOrderByEventTimestampAsc(String userName, String fromDate, String toDate);

}
```
On the start up, index is created like this:

`"FT.CREATE" "com.example.demo.entity.StudentIdx" "ON" "HASH" "PREFIX" "1" "com.example.demo.entity.Student:" "SCHEMA" "userName" "AS" "User-Name" "TAG" "SEPARATOR" "|" "eventTimestamp" "AS" "Event-Timestamp" "NUMERIC" "id" "AS" "id" "NUMERIC" "SORTABLE"`

`Problem 1`

When above repository query is invoked, `monitor` outputs:

` "FT.SEARCH" "com.example.demo.entity.StudentIdx" "@User\\-Name:{pera} @Event\\-Timestamp:[1611995400000 1715851029021]" "SORTBY" "eventTimestamp" "ASC" "LIMIT" "0" "10000"`

Exception is:

`redis.clients.jedis.exceptions.JedisDataException: Property eventTimestamp not loaded nor in schema`

Would it be possible to modify this and make it to be executed as:

` "FT.SEARCH" "com.example.demo.entity.StudentIdx" "@User\\-Name:{pera} @Event\\-Timestamp:[1611995400000 1715851029021]" "SORTBY" "Event-Timestamp" "ASC" "LIMIT" "0" "10000"`

Note: 

I did try:

```
@Indexed(alias = "Event-Timestamp", fieldName = "Event-Timestamp")
 private LocalDateTime eventTimestamp;
```
Same issue.

`Problem 2`

Why in the above `findBy` query "LIMIT" "0" "10000"` is appended when I didn't specify limit anywhere?

```
redis:
  om:
    spring:
      repository:
        query:
          limit: 10000 
```
Why is here limit only 10000?

**Comment by bsbodden** [comment]
I remove the limit part from the issue description, that one is not a bug but a feature :-) See https://redis.io/docs/latest/commands/ft.search/ :
```
LIMIT first num
limits the results to the offset and number of results given. Note that the offset is zero-indexed. **The default is 0 10**, which returns 10 items starting from the first result. You can use LIMIT 0 0 to count the number of documents in the result set without actually returning them.
```

Without a LIMIT the default is 10, so we just gave it a more reasonable default in the app. You can bump it up or down with the above mentioned property up to the `MAXSEARCHRESULTS` value for the server, see https://redis.io/docs/latest/commands/ft.config-get/ which on a docker based Redis stack is:
```
8) 1) MAXSEARCHRESULTS
    2) "10000"
```
I believe on Redis Enterprise/Cloud this might be `1000000`

**Comment by bsbodden** [comment]
@dasivon021 also in the code below:
```
@Repository
@Transactional(readOnly = true)
public interface StudentRepository extends RedisEnhancedRepository<Student, Long>, QueryByExampleExecutor<Student> {

    List<Student> findByUserNameAndEventTimestampBetweenOrderByEventTimestampAsc(String userName, String fromDate, String toDate);

}
```

* `@Transactional(readOnly = true)` has no effect in Spring Data Redis or Redis OM Spring
* The params `String fromDate, String toDate` should be of type `LocalDateTime` not `String`

**Comment by dasivon021** [comment]
@bsbodden Yes, I'm aware about Transactional, left it here by accident, thank you. Actually `String fromDate, String toDate` do have to be strings UTC, passed to the query as:

`var fromDate = String.valueOf(createdAfter.toLocalDateTime().toInstant(ZoneOffset.UTC).toEpochMilli());`
