### ISSUE TITLE
How to implement IN Clause

### ISSUE THREAD

**Issue by shannonantony** [redis/redis-om-spring#45]
Hi, I have a list of employees in my data set. Please let me know how do I write a query to select like

select employees where employeeId in (1,2,3)

Appreciate your help

thanks

Jay

**Comment by bsbodden** [comment]
Jay,
There are a couple of ways you can accomplish that:

1.  You can use the `RedisDocumentRepository#findAllById` (https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html#findAllById-java.lang.Iterable-)

  Here's a sample test:

  https://github.com/redis/redis-om-spring/blob/main/redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/BasicRedisDocumentMappingTest.java#L63

2. If your index property is marked with `@Indexable` you can use a simple finder like the example below:

https://github.com/redis/redis-om-spring/blob/main/demos/roms-permits/src/main/java/com/redis/om/permits/repositories/PermitRepository.java#L34

3. You can also use an `EntityStream` if  your index property is marked with `@Indexable` like the example here:

https://github.com/redis/redis-om-spring/blob/main/redis-om-spring/src/test/java/com/redis/om/spring/search/stream/EntityStreamTest.java#L139

**Comment by shannonantony** [comment]
Thanks for your reply @bsbodden 

Yes. first option works for the id field.
But second option does not work for me

my data sample like

id       employee_id              dept_id
----------------------------------------
1                A                            100
2                B                             200
3                C                             300

If I need to get a list of employee records where dept_id in (100, 200,300)
what should be the query look like?

btw, employee_id and dept_id are @indexed fields

I have the repository code like this

Iterable<MetaData> findByDeptId(Set<String> deptIds);

Please let me know what I am missing and please share a sample working code

thanks

Jay

**Comment by bsbodden** [comment]
It's likely becuase `employee_id` and `dept_id` have a `_` and in Spring the underscore is used to denote a nested field in a query. I've added a JUnit test matching your example above here https://github.com/redis/redis-om-spring/blob/main/redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/BasicRedisDocumentMappingTest.java#L146

Jump on our Discord server for these types of issues and likely to get a quicker answer http://discord.gg/redis

**Comment by shannonantony** [comment]
I repeated the same test in my local and getting empty results for
`Iterable<Metadata> metadata = metadataRepo.findByDeptId(Set.of("C", "B"));`
As in the example, I have 3 records in redisearch. but the query is somehow returning empty
Not sure what am I missing.
thanks again for your help
Jay

**Comment by bsbodden** [comment]
@shannonantony can you provide a reproducer project that I can play with? Thanks

**Comment by shannonantony** [comment]
I basically modified the skeleton app as below

```
public interface MetadataRepository extends RedisDocumentRepository<Metadata, String> {
  Iterable<Metadata> findByDeptId(Set<String> list);
}

```
Also, Added Controller endpoint in PeopleControllerV1 as

 ```
 @GetMapping("findByDeptId")
  public Iterable<Metadata> findByDeptId() {
	    /**
	     * A 100
	     * B 200
	     * C 300
	     */
	  	metadataRepo.deleteAll();
	    Metadata md1 = new Metadata();
	    md1.setDeptId("A");
	    md1.setEmployeeId("100");
	    
	    Metadata md2 = new Metadata();
	    md2.setDeptId("B");
	    md2.setEmployeeId("200");
	    
	    Metadata md3 = new Metadata();
	    md3.setDeptId("C");
	    md3.setEmployeeId("300");
	    
	    metadataRepo.saveAll(Set.of(md1, md2, md3));
	    
	    System.out.println("metadata count: " + metadataRepo.count());
	    
	    Iterable<Metadata> metadata = metadataRepo.findByDeptId(Set.of("C", "B"));
	    // NOTE: order of the results will NOT match the order of the ids
	    //       provided
	    metadata.forEach(System.out::println);
	    
	    return metadata;
	  }
```
Please let me know if you want the whole app? not sure how do I send it though

thanks for looking into my issue

thanks again

Jay

**Comment by bsbodden** [comment]
Yes, if you could just a standalone maven project with main App, the model, the repo and your controller. That way I can run it against a local Redis and see what commands are being issued.

**Comment by bsbodden** [comment]
You can use `redis-cli` with the `MONITOR` flag. Like `redis-cli MONITOR` and like a `tail -f` on the Redis Server.

**Comment by shannonantony** [comment]
I created a separate app and it works now. I need to go back to the original app and find out what went wrong.
Thanks for your guidance and tips!!! very much appreciated !
