### ISSUE TITLE
Pagination not working with search

### ISSUE THREAD

**Issue by rpjtesting** [redis/redis-om-spring#450]
Hi @bsbodden ,

I am trying to paginate data using EntityStream.getSlice() method, but it is not working with search. No query is printed in profiler.
It returns empty list in output.

Below is sample code:
entityStream.of(entityClass)
.filter(predicate)
.getSlice(PageRequest.of(pageOffset, pageLimit)
.collect(Collectors.toList()); // returns empty list

Is there any other way to paginate data ?

**Comment by bsbodden** [comment]
Example of pagination are:
- https://github.com/redis/redis-om-spring/blob/main/redis-om-spring/src/test/java/com/redis/om/spring/search/stream/EntityStreamsAggregationsDocsPagingTest.java
- https://github.com/redis/redis-om-spring/blob/main/redis-om-spring/src/test/java/com/redis/om/spring/search/stream/EntityStreamsAggregationsHashPagingTest.java

**Comment by rpjtesting** [comment]
Hi @bsbodden, 
I have used a simple predicate and model class. 
I am trying to use getSlice method to provide pagination inputs for search(offset and limit). But after going through that method internally, it works only with cursor and not for ft search. 

I am creating ft.search predicate using searchstream and want to paginate the data simply by providing Pageable as input. I am not able to find how to provide offset value using searchstream. 

Also, the links you have provided uses ft.cursor read with aggregate queries, but is it possible to use offset directly for ft.search queries ?
