### ISSUE TITLE
Missing/empty docs in docs directory

### ISSUE THREAD

**Issue by joshrotenberg** [redis/redis-om-spring#465]
This links to the docs directory but the files are empty. It looks like there is already a `Getting Started` section in the REAMDE, so maybe this whole link can just go.

https://github.com/redis/redis-om-spring/blob/08eca0697e4d25716e742999c64b633cac1fec0d/README.md?plain=1#L467

**Comment by bsbodden** [comment]
Thanks, full docs site coming soon using Antora https://antora.org/ - likely on 0.9.4 release
