### ISSUE TITLE
Pagination not working with ft.search

### ISSUE THREAD

**Issue by rpjtesting** [redis/redis-om-spring#471]
Hi @bsbodden,

This issue is in reference to closed issue #450.

I have used a simple predicate and model class.
I am trying to use getSlice method to provide pagination inputs for search(offset and limit). But after going through that method internally, it works only with cursor and not for ft search.

I am creating ft.search predicate using searchstream and want to paginate the data simply by providing Pageable as input. I am not able to find how to provide offset value using searchstream.

Also, the links you have provided uses ft.cursor read with aggregate queries, but is it possible to use offset directly for ft.search queries ?

**Comment by bsbodden** [comment]
@rpjtesting you can paginate today with `skip` and `limit` like:
```java
    int PAGE_SIZE = 2;
    int page = 0;

    // get first page
    List<Company> page0 = entityStream.of(Company.class) //
        .sorted(Company$.NAME) //
        .skip(page * PAGE_SIZE) //
        .limit(PAGE_SIZE) //
        .collect(Collectors.toList());

    assertThat(page0).hasSize(PAGE_SIZE);

    List<String> names0 = page0.stream().map(Company::getName).collect(Collectors.toList());
    assertThat(names0).containsExactly("Microsoft", "RedisInc");

    // get second page
    page = 1;
    List<Company> page1 = entityStream.of(Company.class) //
        .sorted(Company$.NAME) //
        .skip(page * PAGE_SIZE) //
        .limit(PAGE_SIZE) //
        .collect(Collectors.toList());

    assertThat(page1).hasSize(1);

    List<String> names1 = page1.stream().map(Company::getName).collect(Collectors.toList());
    assertThat(names1).containsExactly("Tesla");
  ```
  
  I will add a new method to take a Pageable soon and do what skip and limit are doing internally

**Comment by bsbodden** [comment]
@rpjtesting see https://github.com/redis/redis-om-spring/pull/472

Examples of how to use https://github.com/redis/redis-om-spring/blob/1f2591ab576187ff6d9675f8b2bf99e6cad8031a/redis-om-spring/src/test/java/com/redis/om/spring/search/stream/EntityStreamDocsTest.java#L2763

```java
    int PAGE_SIZE = 2;
    int page = 0;

    var page0Request = PageRequest.of(page, PAGE_SIZE, Sort.by(Company$.NAME));

    // get first page
    Slice<Company> page0 = entityStream.of(Company.class) //
        .getSlice(page0Request);


    assertThat(page0).hasSize(PAGE_SIZE);
    assertThat(page0.hasNext()).isTrue();

    List<String> names0 = page0.stream().map(Company::getName).collect(Collectors.toList());
    assertThat(names0).containsExactly("Microsoft", "RedisInc");

    // get second page
    page = 1;
    var page1Request = PageRequest.of(page, PAGE_SIZE, Sort.by(Company$.NAME));
    Slice<Company> page1 = entityStream.of(Company.class) //
        .getSlice(page1Request);

    assertThat(page1).hasSize(1);
    assertThat(page1.hasNext()).isFalse();

    List<String> names1 = page1.stream().map(Company::getName).collect(Collectors.toList());
    assertThat(names1).containsExactly("Tesla");
```

**Comment by sumitjn-hf** [comment]
@bsbodden Is it possible to get the total number of matched elements along with the slice to construct a Page object containing total elements?

**Comment by bsbodden** [comment]
> @bsbodden Is it possible to get the total number of matched elements along with the slice to construct a Page object containing total elements? I see that we are running the count query [here](https://github.com/redis/redis-om-spring/blob/5396979aa473f5348cf2d4b8f435a4253e922625/redis-om-spring/src/main/java/com/redis/om/spring/search/stream/SearchStreamImpl.java#L735) but the information cannot be captured in a Slice.
> 
> I am actually looking for a getPage instead of getSlice so that the paginated API can return total number of pages/elements.

Next release has a complete replacement of all Slice implementations with Page instead.

**Comment by sumitjainn** [comment]
Thanks a ton, really appreciate the quick turnaround on this!
