### ISSUE TITLE
Scalability concerns using redis om spring

### ISSUE THREAD

**Issue by nhealthlive** [redis/redis-om-spring#482]
Dear,  Redis om spring team @bsbodden  we are using the library for a large-scale application, where millions of data need to be processed with concurrent writes/reads to/from Redis. we are using redis-om-spring extensively throughout all the services,  When we reach a point of stress and load test, a Single node of Redis couldn't handle the load. below are the real-time statistics, We tried to increase the io-threads and VM resources, but unfortunately nothing gives any upper hand to the problem. 

I wish is there a way we can have a clustered environment. If Redis om Spring doesn't support clustering please suggest any workarounds for the time being.

![image](https://github.com/redis/redis-om-spring/assets/109862768/46c40c3c-c1be-4ad7-9ada-6fedf6623acf)

Any advice is highly appreciated, We are kind of blocked at this point.

Thank you :-)

**Comment by bsbodden** [comment]
It's a feature that's at the top of list right now, and slated to be in the 1.0.0 release, so pretty soon.

**Comment by nhealthlive** [comment]
> It's a feature that's at the top of list right now, and slated to be in the 1.0.0 release, so pretty soon.

Great thanks for the response, Looking forward to it, Any ETA ?

**Comment by bsbodden** [comment]
Unfortunately, the OSS cluster mode does not support search properly. So, system that use a proxy to a clustered environment are preferred, something like the Redis Enterprise Proxy https://redis.io/blog/redis-enterprise-proxy/
