### ISSUE TITLE
Unable to filter on entityStream properly

### ISSUE THREAD

**Issue by kmanchev-hedgeserv** [redis/redis-om-spring#486]
Hello,
I encountered the issue of not able to filter on a field from my Object. The object looks like this:
one abstract class that is extended by multiple objects that I am saving in Redis
![image](https://github.com/redis/redis-om-spring/assets/160245484/fa1eca9a-9c13-4e80-9673-20c12d46ab7a)

![image](https://github.com/redis/redis-om-spring/assets/160245484/52206413-b8ed-4232-a28e-b76b52281d67)

the EntityStream code that I try to filter with:

`entityStream.of(ConcreteObjectDTO.class)
            .filter(ConcreteObjectDTO$.CLIENT_CODE.eq("0001QA"))
            .collect(Collectors.toSet());`
In RedisInsight I see the fallowing query:

`
  "FT.SEARCH" "com.path.to.my.dto.ConcreteObjectDTOIdx" "( @clientCode:0001QA)" "LIMIT" "0" "10000" "DIALECT" "1"
`
This query returns 0 entries. 

If I try filtering by id, it works as expected: 
`
entityStream.of(ConcreteObjectDTO.class)
            .filter(ConcreteObjectDTO$.ID.eq("0001QA:some:specific:id"))
            .collect(Collectors.toSet());
`

the query: 
`
"FT.SEARCH" "com.path.to.my.dto.ConcreteObjectDTOIdx" "( @id:{0001QA\\:some\\:specific\\:id})" "LIMIT" "0" "10000" "DIALECT" "1"
`

I tried to edit the original query in redis CLI by adding curly braces to the client code value like this : 

`
  "FT.SEARCH" "com.path.to.my.dto.ConcreteObjectDTOIdx" "( @clientCode:{0001QA})" "LIMIT" "0" "10000" "DIALECT" "1"
` and it works, but I am unable to figure out how to translate it to an entityStream code to behave the same...
We use **redis-om-spring version: 0.9.1** and **java version: 21**

**Comment by bsbodden** [comment]
Either use `@Indexed` or `@Searchable` but not both on the same field. Also `@Id` is by default indexed as TAG so no need to add the `@Indexed` on `@Id`. Use `@Searchble` only if you need full-text search capabilities, for field like `clientCode` you are probably searching by exact value, right?

To troubleshoot it, also provide the `FT.INFO "com.path.to.my.dto.ConcreteObjectDTOIdx"`

**Comment by kmanchev-hedgeserv** [comment]
It worked as expected. Thanks !
