### ISSUE TITLE
JSON documents numeric field values are automatically rounding

### ISSUE THREAD

**Issue by nhealthlive** [redis/redis-om-spring#489]
We have the following @Document model

![image](https://github.com/redis/redis-om-spring/assets/109862768/a1567674-9fe5-4b68-8d77-214890e51e06)

Here the surId is a type of Long, But when we set long-range values, It automatically rounds to x000

That is if I set surId as **_8301034833169298414_** it rounds to **_8301034833169298000_**

If I set surId as **_8301034833169297919_** it rounds to **_8301034833169297000_**

![image](https://github.com/redis/redis-om-spring/assets/109862768/755f171c-cb6c-4851-8f93-80727892342a)

This can be try from the redis insight.

Is there any range limit for NumericField? Any workarounds that you can suggest @bsbodden 

- Redis OM Spring Version : 0.8.7
- Module versions
RediSearch v. 2.8.9
RedisJSON v. 2.6.7
- Redis Standalone Version: 7.2.3
- Spring boot version : 3.1.3

**Comment by bsbodden** [comment]
Unfortunately this is a JSON engine limitation, as the image below shows it happens on insertion. One possible workaround would be to tell Spring to serialize and store it as a string, but then you won't be able to indexed as a number, so features like range indexes would work

see related https://www.techempower.com/blog/2016/07/05/mangling-json-numbers/

<img width="1316" alt="Screenshot 2024-07-10 at 11 04 25 PM" src="https://github.com/redis/redis-om-spring/assets/24109/ccb072ce-3c85-468b-b4c3-2a17eeca666a">
