### ISSUE TITLE
[Bug] Search query is not getting generated for `@Indexed` annotation

### ISSUE THREAD

**Issue by Suvink** [redis/redis-om-spring#492]
### Observed behaviour
I have the following Document model: 

```java
public class OAuth2Authorization implements Serializable {

    @Indexed
    @NonNull
    @Id
    private String id;

    @Indexed
    private String authorizationCodeValue;

    ... other properties
}
```

When I start my server up, I observe the following index being created from the Redis Insights profiler:
```bash
14:26:51.101 [0 172.17.0.1:43772] "FT.CREATE" "com.my.path.OAuth2AuthorizationIdx" "ON" "JSON" "PREFIX" "1" "OAuth2Authorization" "LANGUAGE" "english" "SCHEMA" "$.id" "AS" "id" "TAG" "SEPARATOR" "|"
```
Note that this does not include the `authorizationCodeValue` field.

Then I've defined a repository method to fetch an object by the `authorizationCodeValue`:
```java
public interface OAuth2AuthorizationRepository extends RedisDocumentRepository<OAuth2Authorization, String> {
    List<OAuth2Authorization> findByAuthorizationCodeValue(String authorizationCodeValue);
}
```

When I execute this method, it returns empty and I observe the following query being executed in the profiler:
```bash
14:28:48.658 [0 172.17.0.1:49360] "FT.SEARCH" "com.my.path.OAuth2AuthorizationIdx" "" "LIMIT" "0" "10000"
```

Note that the actual search query is empty.

However, when I add `@Searchable` annotation to the model in addition to the `@Indexed` annotation, I see the index correctly being configured and the query being constructed properly. I did not use `@Searchable` because I don't have a requirement for full-text capabilities and just want to match the entire value.

```bash
14:30:02.071 [0 172.17.0.1:45392] "FT.CREATE" "com.my.path.OAuth2AuthorizationIdx" "ON" "JSON" "PREFIX" "1" "OAuth2Authorization" "LANGUAGE" "english" "SCHEMA" "$.authorizationCodeValue" "AS" "authorizationCodeValue" "TEXT" "$.id" "AS" "id" "TAG" "SEPARATOR" "|"
```
```bash
14:32:33.361 [0 172.17.0.1:60450] "FT.SEARCH" "com.my.path.OAuth2AuthorizationIdx" "@authorizationCodeValue:FETPuFaWQpumP5yip_pyOpblxDDdeht7ihiDdBGbLEeuksxzao_Fi2JNFWPAZ5USmguO5JVq11jiTJzLWhsAa18yL3Zury_GIxi9JPHDQEyHU\\-67A0V5XFOWtnfK1UNi" "LIMIT" "0" "10000"
```

### Expected behaviour

When a field is annotated with `@Indexed` annotation, the correct index and the search query should be created. 

### Additional Info:
- ROMS version: `0.8.6`
- Spring Data Redis version: `3.3.2`
- Redis CLI version: `7.2.5`

**Comment by bsbodden** [comment]
It should work, don't see anything weird in the code that would prevent the field from getting indexed. The field in the entity must have a getter/setter as per JavaBean conventions. And you can drop the `@Indexed` from the id field, but other than that it looks fine.

**Comment by bsbodden** [comment]
@Suvink did you resolve this?

**Comment by cmingfai** [comment]
I am following the page [https://redis.io/learn/develop/java/spring/redis-om/redis-om-spring-hash](url) to learn the ROMS tutorial and found similar issue that ```@Indexed``` annotated domain entity fields do not have index created (by checking output of "redis-cli monitor") . 

If I ```import org.springframework.data.redis.core.index.Indexed``` ( like the example User class in the tutorial page), the ```@Indexed``` annotated field do not have expected indexes created. Using the same "curl" commands from the tutorial produce different and strange results.

However, if I ```import com.redis.om.spring.annotations.Indexed```, the related indexes are created (by checking output of "redis-cli monitor") and the "curl" commands produce same results.

So, you may check if you are importing org.springframework.data.redis.core.index.Indexed. If yes, try import com.redis.om.spring.annotations.Indexed to see if it works.

I am using ROMS 0.9.7:

```xml
<dependency>
    <groupId>com.redis.om</groupId>
    <artifactId>redis-om-spring</artifactId>
    <version>0.9.7</version>
</dependency>
```

Domain entity class:

```java
package com.redis.om.hashes.domain;

import org.springframework.data.annotation.Id;
import org.springframework.data.redis.core.RedisHash;
// doesn't work
// import org.springframework.data.redis.core.index.Indexed;

// worked, drop the index if it was created earlier using the following command
// ft.dropIndex com.redis.om.hashes.domain.UserIdx
import com.redis.om.spring.annotations.Indexed;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;

@Data
@RequiredArgsConstructor(staticName = "of")
@AllArgsConstructor(access = AccessLevel.PROTECTED)
@NoArgsConstructor
@RedisHash
public class User {
  @Id
  private String id;

  @Indexed @NonNull
  private String firstName;

  @Indexed
  private String middleName;

  @Indexed @NonNull
  private String lastName;

  @NonNull
  @Indexed
  String email;
}
```

**Comment by Suvink** [comment]
Hey @cmingfai ,
Yes you're right. I imported the annotation from `org.springframework.data.redis.core.index.Indexed`. Let me write a sample app and see if I can produce the same result (we've moved away from ROMS a while back). Thanks a lot for this!

**Comment by Suvink** [comment]
> @Suvink did you resolve this?

Hey @bsbodden, apologies for the late response. At the moment, we can keep this closed and if we find an issue with the annotation, I'll re-open the issue with more details.
