### ISSUE TITLE
 with not being able to retrieve data using @query.

### ISSUE THREAD

**Issue by w9931125** [redis/redis-om-spring#497]
Thank you very much to the development team for providing a more lightweight search solution. However, I've encountered some issues and hope to get some help:

I'm using Java 21, Spring Boot 3.3.0, and redis-om-spring 0.9.4. After extending the `RedisDocumentRepository` class, I overrode the `page` method (I didn’t seem to find any examples with conditions applied to the `page` method). I used the `@Query` annotation to query with the email as a parameter condition. Additionally, in the `UserPageVO`, I declared the email field with `@Indexed` and `@Searchable`, but it still doesn't return any results. 
![image](https://github.com/user-attachments/assets/0f49bb2d-baae-4380-a443-b88ae4b7cfd1)
![image](https://github.com/user-attachments/assets/b7aea211-a6ec-48fd-b8ec-64bfc5420919)
![image](https://github.com/user-attachments/assets/e5a368dc-32dd-4213-8b34-c9fc53bececf)
![image](https://github.com/user-attachments/assets/be68b67e-a7da-4b54-a276-cd1478c35d2e)
![image](https://github.com/user-attachments/assets/77fbc6e3-0efe-4323-aee7-a6c82335247b)

**Comment by bsbodden** [comment]
Glad you figured it out. If you want some suggestions post your code and some sample data. Cheers, bsb
