### ISSUE TITLE
Using Lettuce with redis-om-spring

### ISSUE THREAD

**Issue by shannonantony** [redis/redis-om-spring#502]
@bsbodden,
Thank you for your hard work and for supporting the Redis community.

I have a question regarding Redis-OM-Spring. Specifically, I would like to know if Redis-OM-Spring supports the Lettuce library. Given that Lettuce is the default client in Spring Boot, and it offers valuable features such as inherent thread safety and replica load balancing, particularly when used with Redis Sentinel.

If Lettuce is not currently supported, are there any plans to include this support in future releases?

Thank you 
Jay

**Comment by bsbodden** [comment]
See https://github.com/redis/redis-om-spring/issues/426
