### ISSUE TITLE
The difference between Declarative Search Indices and Full-text Search Indices

### ISSUE THREAD

**Issue by BrightFutureSugar** [redis/redis-om-spring#52]
Full-text Search can search for data through findBy*StartingWith But Declarative Search Indices can't. I want to know the difference.
Name is  Full-text Search Indices. Color is Declarative Search Indices.
    Optional<Phone> findOneByName(@Param("name")String name);
    Can get results

    @Query("@name:{$name}")
    Optional<Phone> findOneByName(@Param("name")String name);
    Can't get results.  @Query don't take effect.

    @Query("@color:{$color}*")
    Iterable<Phone> findByColorStartingWith (String color);
    or
    Iterable<Phone> findByColorStartingWith (String color);
    Can't get results.  findBy*StartingWith don't take effect.

**Comment by bsbodden** [comment]
@BrightFutureSugar can you post an example of your Phone entity? I'm not sure I get the questions but here's a guess. Entity fields marked with `@Searchable` are used to create a TEXT index while fields marked with `@Indexable` are either TAG, GEO or NUMERIC (depending on the Java datatype). The startingWith searches only work on fields marked as `@Searchable` (TEXT), see https://redis.io/docs/stack/search/reference/query_syntax/#prefix-matching 

There is an example here https://github.com/redis/redis-om-spring/blob/main/demos/roms-documents/src/main/java/com/redis/om/documents/repositories/CompanyRepository.java#L32

Where the `name` field is marked with `@Searchable` https://github.com/redis/redis-om-spring/blob/main/demos/roms-documents/src/main/java/com/redis/om/documents/domain/Company.java#L34

The `@Query` annotation does not care what the name of the method is, it only cares about the params matching the literal query being passed and the result data type. 

For example:

```
  /**
   * > FT.SEARCH idx '@title:hello @tag:{news}' 1) (integer) 1 2) "doc1" 3) 1) "$"
   * 2) "{\"title\":\"hello world\",\"tag\":[\"news\",\"article\"]}"
   */
  @Query("@title:$title @tag:{$tags}")
  Iterable<MyDoc> findByTitleAndTags(@Param("title") String title, @Param("tags") Set<String> tags);
```

This method could be name `doTheThingForMe(@Param("title") String title, @Param("tags") Set<String> tags);` and as long as the `$title` and the  `$tags` have matching `@Params` all is well.

**Comment by BrightFutureSugar** [comment]
Thank you for your answer. I got it.
