### ISSUE TITLE
JSON.SET twice

### ISSUE THREAD

**Issue by SylvainAssemat** [redis/redis-om-spring#529]
HI all

I worked on the implementation of the spring "MessageListener" to listen redis event.

I can catch all the notification, but i remark that i get it **twice** on a simple "save" use case.

CHANNEL : __keyevent@0__:json.set - fr.gms.legacy.api.redis.model.core.RDUser:806f8723-49cf-4fd6-b2c6-b54658bf8515
CHANNEL : __keyevent@0__:json.set - fr.gms.legacy.api.redis.model.core.RDUser:806f8723-49cf-4fd6-b2c6-b54658bf8515

I was thinking by my side, i was calling the save method twice but ... no.
```public interface RDUserRepository extends RedisDocumentRepository<RDUser, String>```

I can not identify what the cause , maybe do you experiment the same or do you have any advice ?

(Based on the REDIS INSIGHT MONITOR, seeing 2 times JSON.SET)

Thanks

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

Update the saveAll method in SimpleRedisDocumentRepository to perform a single JSON.SET operation per entity, preventing duplicate notifications. This change ensures that only one notification is sent for each save operation.

You can review changes in this commit: https://github.com/wwqwq2313/redis-redis-om-spring-529/commit/92d84423e9076b6385354253f59af13aa75c809b.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
