### ISSUE TITLE
Adding support for more options for Ids

### ISSUE THREAD

**Issue by pierrelambert** [redis/redis-om-spring#54]
It would be nice to have support for implicit Id for instance the field value of a document would be used as key. 
I imagine it would be a new annotation like @RedisId.
This should not prevent to use a prefix either coming from the Document annotation content either clearly stated in the Id annotation. 

It would as well be nice to have the ability to generate a sequential Id.

**Comment by bsbodden** [comment]
@pierrelambert can you come up with a simple example, to get a better idea? Currently, I believe that if you mark a field with `@Id` and set the values before calling `repository.save(entity)` the set value is respected. Does that cover the scenario above?

**Comment by pierrelambert** [comment]
Maybe I missed something and need to re-test it, but to me from the moment you use @Id it will generate a UID for the field value and in the key name.
