### ISSUE TITLE
how to rebuild index on application startup

### ISSUE THREAD

**Issue by snipercy** [redis/redis-om-spring#74]
when I modify a Domain(eg:Company) which annotation `@Document` ，when application start , it check index (eg:com.xxx.CompanyIdx) , if the index is already exist, it will skip build new index.  How to rebuild index？

**Comment by bsbodden** [comment]
Hi, at this moment the only way to trigger the index rebuild is to remove the index using `FT.DROPINDEX myindex` https://redis.io/commands/ft.dropindex/

This is so in production DevOps can control the index management and we don't trigger a reindex on a massive keyspace. We are looking into an index migration type of feature in the future.
