### ISSUE TITLE
Exception with Spring Boot 2.7.2

### ISSUE THREAD

**Issue by restoreddev** [redis/redis-om-spring#86]
I'm trying to use `redis-om-spring` with Spring Boot 2.7.2 and OpenJDK 18. Whenever I add the `@EnableRedisDocumentRepositories` annotation to my application class, I get the following exception on build: `java.lang.IllegalArgumentException: No attribute named messageListenerContainerRef found`. I don't see any documentation about the `messageListenerContainerRef` or how to set it. Am I using the wrong version of Spring Boot or am I missing something else? Thanks!

**Comment by bsbodden** [comment]
We're tethered to 2.7.0 at the moment, I'll catch up with 2.7.2 in release 0.7.0. Thanks for reporting!

**Comment by PiseyPhal** [comment]
Hi Brother!

I am really also missing about the **messageListenerContainerRef**.

How about now?

**Comment by PiseyPhal** [comment]
> I'm trying to use `redis-om-spring` with Spring Boot 2.7.2 and OpenJDK 18. Whenever I add the `@EnableRedisDocumentRepositories` annotation to my application class, I get the following exception on build: `java.lang.IllegalArgumentException: No attribute named messageListenerContainerRef found`. I don't see any documentation about the `messageListenerContainerRef` or how to set it. Am I using the wrong version of Spring Boot or am I missing something else? Thanks!

Problem was solved?

**Comment by bsbodden** [comment]
0.6.0 will work with 2.7.2 for now the highest Spring Boot version supported is 2.7.0

**Comment by PiseyPhal** [comment]
> 0.6.0 will work with 2.7.2 for now the highest Spring Boot version supported is 2.7.0

Thank, appreciate it!
